const articlesData = {
  status: true,
  data: {
    currentPage: 1,
    data: {
      category: {
        _id: '24990',
        label: 'About',
        permalink: 'about',
        parentId: 0,
        status: 'public',
        createdBy: '432',
        createdAt: '2020-07-06T11:02:58.806Z',
        updatedBy: '432',
        updatedAt: '2020-07-06T11:02:58.806Z',
        categories: [
          {
            _id: '24990',
            label: 'About',
            permalink: 'about',
            parentId: 0,
            status: 'public',
            createdBy: '432',
            createdAt: '2020-07-06T11:02:58.806Z',
            updatedBy: '432',
            updatedAt: '2020-07-06T11:02:58.806Z',
          },
        ],
        children_categories: [],
      },
      articles: [
        {
          updatedBy: '531',
          label: ' St. Patrick’s College Maynooth',
          content:
            '<p>To find out more about St. Patrick’s College, Maynooth visit their <a href="https://maynoothcollege.ie/" target="_blank">homepage</a>.</p>',
          highlight: false,
          createdAt: '2020-04-02T13:15:52.953Z',
          highlightOrder: 0,
          createdBy: '532',
          featuredImage: '25286',
          _id: '15120',
          category: [24990],
          permalink: 'spcm-about',
          status: 'public',
          teaser:
            "<p>The Royal Catholic College of St Patrick was founded in 1795, by act of the Irish Parliament. It was intended to replace the network of Irish continental colleges whose activities were severely curtailed by the French Revolution. The college trained Catholic clergy and it also housed, for a time, a lay college. In 1896, to mark its centenary, a Pontifical University was  established on the campus, with courses in philosophy, theology and canon law. About a decade later, in 1908, the college became a recognised college of the Royal University of Ireland, forerunner of the National University of Ireland. In the 1960s, the college's faculties of arts, science, philosophy and celtic studies faculties began to accept non-ecclesiastical students, with the seminary and pontifical univeristy continuing to operate as before. By the Universities act of 1997, the college's arts, science, philosophy and celtic studies faculties were erected into an independent college of the National University of Ireland, called the National University of Ireland Maynooth. St Patrick's College continues to function as a seminary, with theology degrees conferred by the Pontifical University. </p>",
          updatedAt: '2021-08-24T11:05:07.795Z',
          systemLabels: ['Article'],
          featuredImageDetails: {
            _id: '25286',
            filename: 'spcm-logo.jpg',
            type: 'image',
            year: 2020,
            month: 7,
            hashedName: '98c209524b4785a2a37c110934a913e1.jpg',
            paths: [
              {
                path: 'http://localhost:5100/uploads/2020/7/images/98c209524b4785a2a37c110934a913e1.jpg',
                pathType: 'source',
              },
              {
                path: 'http://localhost:5100/uploads/2020/7/thumbnails/98c209524b4785a2a37c110934a913e1.jpg',
                pathType: 'thumbnail',
              },
            ],
            createdBy: '432',
            createdAt: '2020-07-06T11:03:28.864Z',
            updatedBy: '432',
            updatedAt: '2020-07-06T11:03:28.864Z',
            label: 'undefined',
          },
          author: 'Richard Fitzpatrick',
        },
        {
          updatedBy: '532',
          label: 'About Clericus',
          content:
            '<div>\n<div>Clericus is a digital humanities research project that aims to develop a database on the Irish clerical population for the early modern and modern periods. Phase I of the project, financed by St. Patrick\'s College Maynooth (SPCM), focused on the students and faculty of St. Patrick\'s College, historically Ireland\'s largest seminary and pontifical university. The principal sources used were class portraits and student lists compiled by Monsignor Patrick J. Hamell and Cora Fennelly. This combined dataset provides just under <strong>20,000</strong> individual biographical entries. In line with data protection recommendations, all class portraits and biographical entries up to and including 1945 are available via the website\'s database (48 <a href="../classpieces">class portraits</a> and approximately <strong>14,000</strong> entries).</div>\n<div> </div>\n</div>\n<div>\n<p>September 2020 marked the beginning of Phase II of the Clericus Project. Over the following months the project expanded its database on the Irish clerical population and digital preservation initiative through collaboration with several new institutions. The project first sought to expand the database’s existing information on clerical students through the addition of biographical data relating to the ministry of a subset of the clerical population based in the Diocese of Meath.The Clericus team extracted relevant data from the well-known and recently updated <a href="../resource/55466"><em>History of the Diocese of Meath, 1860-1993</em></a>. In total, over <strong>750</strong> new biographical entries were created for the period 1690 to 1941.</p>\n<p>Apart from deepening our understanding of individual career paths and networks, this work package permitted the project to further test, develop and showcase the database’s dynamic qualities through the integration and synergy of data from several heterogeneous sources. This, in turn, offered the practical experience and customised system necessary to handle a range of new sources and data during future stages of the project. </p>\n<p>Following the successful completion of the Meath work package, Clericus expanded its spatial/geographical range by focusing on the international dimension of the Irish Catholic Church and its clergy. This came in the form of a collaborative project with the Irish Cultural Centre, Paris and members of the academic research community. The project was kindly provided with a dataset compiled by Dr Liam Chambers and Dr Sarah Franks on the student population of the <a href="../resource/63451">Irish College Paris (ICP)</a>. This dataset was compiled using student records from the college’s archives (available <a href="https://archives-en.centreculturelirlandais.com/archives-en">here</a>), and included over <strong>2,000</strong> student entries covering the period 1832 up to the college’s evacuation at the outbreak of World War II. This represents a rich source of information regarding the biographies of individual students, such as information relating to dates of birth, baptism, confirmation, subjects studied and other observations. The value of the data to members of the public researching their family history is increased due to the inclusion of parents\' names (including maiden names) for over half of the students. Almost <strong>200</strong> ICP students would also spend time studying at St Patrick\'s College Maynooth (SPCM), which in turn deepens our understanding of individual formation and career paths. One excellent example to highlight this enrichment process is seen in <a href="9027">Kevin Clark</a> of Meath diocese, whose database entry draws on information from every resource utilised within the Clericus system up until that point.</p>\n<p>The second phase also saw the project expand its temporal range to include data from the early modern period. Several of the most comprehensive records for Ireland’s seventeenth- and eighteenth-century Catholic clergy were identified. As part of this process, the Clericus team recently completed the ingestion of over <strong>1,500</strong> new biographical entries relating to Irish clerical students from the Universities of Paris and Toulouse during the period 1573 to 1792. This data is drawn from the impressive prosopography on the Irish student community created by <a href="../resource/86488">L. W. B. Brockliss and Patrick Ferté</a>. Many of these students were tied to the Irish College Paris (ICP), and the ingestion of this data expands our database to include a large percentage of the individuals who attended the seminary college across the almost four centuries of its existence. Completing this work package has provided the Clericus team with the experience and knowledge necessary to undertake similar work packages on the numerous other Irish colleges active on the continent during the early modern and modern periods. This includes ongoing work being carried out on the ordinations of Irish students in Lisbon and oaths taken by the student body of the Irish College Salamanca. Part of this process has also involved work on a data template to help standrdise and streamline the ingestion of data into the Clericus database.</p>\n<p>No research on the early modern clergy would be complete without having covered Ireland\'s penal laws. Our understanding of the impact of these restrictions on the Catholic Church has advanced greatly over the last fifty years or so. However, the number and identities of the Catholic clergy active on the Irish mission during the ‘Long eighteenth century’ remains unclear. One aim of the Clericus project has been to help fill this lacuna in our knowledge by compiling the first comprehensive database on this population. The Clericus system is ideally suited to completing this important task, while the dynamic nature of our system and data model permits us to identify, capture and chart the social and professional networks, both clerical and lay, that these individuals maintained across Ireland and the continent. This will add layers of complexity and nuance to our data and subsequent understanding of the worlds navigated by thousands, if not tens of thousands of these individuals. </p>\n<p>The first building block of this monumental undertaking was a dataset compiled from the <a href="../article/irelands-popish-parish-priest-in-1704-">1704 clergy registration</a>. Access to a rare copy of this document was kindly provided to the Clericus team by the archivists of The Honourable Society of King’s Inn, Dublin. The registration of Ireland’s ‘Popish Parish Priests’ in 1704 represents one of the most valuable records concerning the island’s eighteenth-century Catholic clergy – the document covers the entire country for one year and provides relatively detailed information on each cleric. This includes their name, place of abode, parish(es), date of ordination, where they received orders, from whom (i.e. bishop) and two lay individuals acting as sureties or guarantors for each priest. In total, the document lists <strong>1,089</strong> priests, just over <strong>800</strong> lay sureties and several dozen Irish and foreign bishops. Carrying out this work package made it necessary to expand the number of organisations (i.e. townlands, parishes and dioceses) and spatial locations within the Clericus system, including many examples found outside of Ireland. This process also led to the further development of the system’s taxonomy, with the number of event types and relation types in particular having grown to meet the demands imposed by such a sizeable and complex dataset.</p>\n<p>Following the ingestion of this data, work on the Clericus system briefly moved away from large datasets to focus instead on smaller, more numerous resources. The aim behind this was to further enrich individual careers to a degree not yet seen in the database by providing granular biographical data and important network linkages between entries within the system. To achieve this, a selection of documents relating to the clergy of Dublin diocese covering twenty years either side of 1704 was chosen. This included a government census of <a href="../article/sculking-about-the-towne-the-clergy-of-dublin-diocese-in-1698">Dublin’s clergy in 1698</a>, a <a href="../article/lobbying-and-last-wills-and-testaments">testimony and will</a> relating to Bishop <a href="77739">John Dempsey</a> from 1693 and 1703 respectively and a second will from c.1728 belonging to an associated cleric, <a href="76511">Dominic Edward Murphy</a>. The work carried out enriching their biographical entries has provided the testbed and framework necessary to undertake similar work packages relating to other biographical entries already present in the Clericus system. </p>\n<p>Earlier this year the Clericus team was joined by Dr Ciaran Reilly as part of a project that seeks to utilise the <a href="../article/obituaries-as-a-source-for-clericus-">obituaries</a> of Maynooth educated priests as a source of information to help further enrich biographical entries contained within the database. To date over <strong>350</strong> obituaries have been identified from c.1860-1900 which relate to clerics already entered in the Clericus database. While this is admittedly a small sample, the obituaries as a source are quite revealing. These obituaries allow the potential to further expand the dataset and establish networks based on associational culture and/or familial connections. In addition, similar biographical information is also present in month’s mind notices, notices of charitable bequests and others reports, but these are not as common as obituaries. From an international perspective, these obituaries provide important information on clerics who ministered in the <a href="../article/maynooth-clerics-in-st-louis">USA</a>, Canada, Australia and New Zealand, revealing the key roles such individuals played in establishing the Catholic Church in these countries.</p>\n<p>Finally, between October and December of this year, the Clericus project will once again turn its focus to the student population of an Irish seminary. With the assistance of a Kevin B. Nolan Digitisation Grant from the Royal Irish Academy (RIA), the Clericus team will capture and ingest student data and class portraits belonging to St. Kieran’s College, Kilkenny. Between 1793 and 1994, St. Kieran’s acted as one of Ireland’s nine diocesan seminaries and educated several thousand clerical students over the course of two centuries. Of the estimated <strong>2,000</strong> who were ultimately ordained for the priesthood, almost two-thirds were dispatched to missions in the United States, Great Britain, Australia and various other countries. Furthermore, this digitisation initiative will also provide members of the Irish public and diaspora with an accessible and interactive digital platform through which to undertake genealogical research.</p>\n<p>To read more about the project and its content, please see the \'<a href="../article-category/articles">Articles</a>\' section on the Clericus website. Alternatively, visitors to the website can view recent news items on our homepage and/or read about specific priests under \'Highlights\'.</p>\n<p> </p>\n<p>The project\'s team are:</p>\n<p>Prof Thomas O\'Connor, Principal Investigator</p>\n<p>Stavros Angelis, Chief Technical Officer</p>\n<p>Dr Ciaran Reilly, Research Assistant</p>\n<p>Dr Richard Fitzpatrick, Research Assistant &amp; Content Manager </p>\n<p>September 2021</p>\n</div>',
          createdAt: '2020-06-15T10:35:32.899Z',
          highlight: false,
          highlightOrder: 0,
          featuredImage: '43963',
          createdBy: '432',
          _id: '22942',
          permalink: 'about',
          category: [24990],
          status: 'public',
          teaser:
            "<div>\n<p>Clericus is a digital humanities research project that aims to develop a database on the Irish clerical population for the early modern and modern periods. Phase I of the project, financed by St. Patrick's College Maynooth (SPCM), focused on the students and faculty of St. Patrick's College, historically Ireland's largest seminary and pontifical university. The principal sources used were class portraits and student lists. Phase II of the project seeks to expand the Clericus database through the addition of new datasets from various sources dating as far back as the sixteenth century.</p>\n</div>\n<div>\n<p> </p>\n</div>",
          updatedAt: '2021-10-08T09:18:25.163Z',
          systemLabels: ['Article'],
          featuredImageDetails: {
            _id: '43963',
            filename: 'cos-logo-bw.jpg',
            type: 'image',
            year: 2020,
            month: 6,
            hashedName: 'af426e8dcbc3255968c893dd892898d3.jpg',
            paths: [
              {
                path: 'http://localhost:5100/uploads/2020/6/images/af426e8dcbc3255968c893dd892898d3.jpg',
                pathType: 'source',
              },
              {
                path: 'http://localhost:5100/uploads/2020/6/thumbnails/af426e8dcbc3255968c893dd892898d3.jpg',
                pathType: 'thumbnail',
              },
            ],
            createdBy: '432',
            createdAt: '2020-06-24T11:02:24.964Z',
            updatedBy: '432',
            updatedAt: '2020-06-24T11:02:24.964Z',
            label: 'undefined',
          },
          author: 'Admin',
        },
        {
          updatedBy: '53930',
          label: 'Arts and Humanities Institute ',
          content:
            '<p>The Clericus research project is housed in Maynooth University’s Arts and Humanities Institute. Founded in 2018, MUAHI is the research home of the Faculty of Arts, Celtic Studies and Philosophy. It is dedicated to the promotion of scholarship within the Faculty and to bringing the best of Maynooth University\'s rich tradition in humanities research to the world.</p>\n<p>To find out more about MUAHI visit their <a href="https://www.maynoothuniversity.ie/arts-and-humanities-institute" target="_blank">homepage</a>.</p>',
          highlight: false,
          createdAt: '2020-04-02T13:02:22.707Z',
          highlightOrder: 0,
          featuredImage: '33537',
          createdBy: '532',
          _id: '15116',
          category: [24990],
          permalink: 'arts-and-humanities-institute-about',
          status: 'public',
          teaser:
            "<p>The Clericus research project is housed in Maynooth University’s Arts and Humanities Institute. Founded in 2018, MUAHI is the research home of the Faculty of Arts, Celtic Studies and Philosophy. It is dedicated to the promotion of scholarship within the Faculty and to bringing the best of Maynooth University's rich tradition in humanities research to the world.</p>",
          updatedAt: '2021-06-11T11:52:07.465Z',
          systemLabels: ['Article'],
          featuredImageDetails: {
            _id: '33537',
            filename: 'logo-transparentx400.jpg',
            type: 'image',
            year: 2020,
            month: 7,
            hashedName: '196b7c4b3f5674a03158e2733faadcb2.jpg',
            paths: [
              {
                path: 'http://localhost:5100/uploads/2020/7/images/196b7c4b3f5674a03158e2733faadcb2.jpg',
                pathType: 'source',
              },
              {
                path: 'http://localhost:5100/uploads/2020/7/thumbnails/196b7c4b3f5674a03158e2733faadcb2.jpg',
                pathType: 'thumbnail',
              },
            ],
            createdBy: '432',
            createdAt: '2020-07-02T10:59:18.939Z',
            updatedBy: '432',
            updatedAt: '2020-07-02T10:59:18.939Z',
            label: 'undefined',
          },
          author: 'Richard Fitzpatrick',
        },
        {
          updatedBy: '53930',
          label: 'Maynooth University',
          content:
            '<p>Since its establishment in 1997, Maynooth has evolved into one of Ireland’s fastest growing universities. It is home to a vibrant community of almost 1,000 researchers spread across the arts, sciences, engineering and social sciences. Clericus is just one of over 500 externally funded research projects hosted by Maynooth, and the project seeks to develop the university’s growing reputation in the area of digital humanities and interdisciplinary research. </p>\n<p>To find out more about Maynooth University visit their <a href="https://www.maynoothuniversity.ie" target="_blank">homepage</a>.</p>',
          highlight: false,
          createdAt: '2020-04-02T13:23:05.982Z',
          highlightOrder: 0,
          featuredImage: '25291',
          createdBy: '532',
          _id: '14949',
          category: [24990],
          permalink: 'about-maynooth-university',
          teaser:
            '<p>Since its establishment in 1997, Maynooth has evolved into one of Ireland’s fastest growing universities. It is home to a vibrant community of almost 1,000 researchers spread across the arts, sciences, engineering and social sciences. Clericus is just one of over 500 externally funded research projects hosted by Maynooth, and the project seeks to develop the university’s growing reputation in the area of digital humanities and interdisciplinary research. </p>',
          status: 'public',
          updatedAt: '2021-06-11T11:52:17.465Z',
          systemLabels: ['Article'],
          featuredImageDetails: {
            _id: '25291',
            filename: null,
            type: 'image',
            year: 0,
            month: 0,
            paths: [
              {
                path: 'http://localhost:5100/uploads/0/0/images/undefined',
                pathType: 'source',
              },
              {
                path: 'http://localhost:5100/uploads/0/0/thumbnails/undefined',
                pathType: 'thumbnail',
              },
            ],
            createdBy: null,
            createdAt: null,
            updatedBy: null,
            updatedAt: null,
          },
          author: 'Richard Fitzpatrick',
        },
      ],
    },
    totalItems: 4,
    totalPages: 1,
  },
  error: [],
  msg: 'Query results',
};
export default articlesData;
