export const carouselData = {
  status: true,
  data: {
    data: [
      {
        createdAt: '2021-04-23T10:15:41.186Z',
        image: '72750',
        updatedBy: '532',
        createdBy: '532',
        caption: 'Library',
        _id: '72751',
        label: 'Irish Cultural Centre (Paris)',
        url: '',
        status: 'public',
        order: 1,
        updatedAt: '2021-09-02T13:45:12.606Z',
        systemLabels: ['Slideshow'],
        imageDetails: {
          _id: '72750',
          filename:
            'Centre Culturel Irlandais Bibliotheque patrimoniale (c) Julien Mouffron-Gardner-5633.jpg',
          type: 'image',
          year: 2021,
          month: 4,
          hashedName: 'ebe4be6d0bb829fb373bec744873700e.jpg',
          paths: [
            {
              path: 'http://localhost:5100/uploads/2021/4/images/ebe4be6d0bb829fb373bec744873700e.jpg',
              pathType: 'source',
            },
            {
              path: 'http://localhost:5100/uploads/2021/4/thumbnails/ebe4be6d0bb829fb373bec744873700e.jpg',
              pathType: 'thumbnail',
            },
          ],
          createdBy: '532',
          createdAt: '2021-04-23T10:15:25.228Z',
          updatedBy: '532',
          updatedAt: '2021-04-23T10:15:25.228Z',
          label: 'undefined',
        },
      },
      {
        createdAt: '2021-09-02T10:14:02.067Z',
        image: '55132',
        updatedBy: '532',
        createdBy: '532',
        caption: "St. Kieran's College, Kilkenny",
        _id: '86247',
        label: 'Chapel',
        url: '',
        status: 'public',
        order: 1,
        updatedAt: '2021-09-02T13:45:54.795Z',
        systemLabels: ['Slideshow'],
        imageDetails: {
          _id: '55132',
          filename: "St Kieran's Chapel Cropped.jpg",
          type: 'image',
          year: 2021,
          month: 9,
          hashedName: '7a6429ac0c109a41b1baed7ebc181669.jpg',
          paths: [
            {
              path: 'http://localhost:5100/uploads/2021/9/images/7a6429ac0c109a41b1baed7ebc181669.jpg',
              pathType: 'source',
            },
            {
              path: 'http://localhost:5100/uploads/2021/9/thumbnails/7a6429ac0c109a41b1baed7ebc181669.jpg',
              pathType: 'thumbnail',
            },
          ],
          createdBy: '532',
          createdAt: '2021-09-02T10:17:04.360Z',
          updatedBy: '532',
          updatedAt: '2021-09-02T10:17:04.360Z',
          label: 'undefined',
        },
      },
    ],
    totalItems: 2,
  },
  error: [],
  msg: 'Query results',
};

export const genericStatsData = {
  status: true,
  data: {
    people: 23683,
    resources: 4294,
    dioceses: 298,
    lastNames: 5182,
    organisations: 4337,
    events: 30119,
    spatial: 537,
    temporal: 10003,
    classpieces: 70,
  },
  error: false,
  msg: '',
};

export const about = {
  status: true,
  data: {
    _id: '22942',
    label: 'About Clericus',
    permalink: 'about',
    category: [24990],
    content:
      '<div>\n<div>Clericus is a digital humanities research project that aims to develop a database on the Irish clerical population for the early modern and modern periods. Phase I of the project, financed by St. Patrick\'s College Maynooth (SPCM), focused on the students and faculty of St. Patrick\'s College, historically Ireland\'s largest seminary and pontifical university. The principal sources used were class portraits and student lists compiled by Monsignor Patrick J. Hamell and Cora Fennelly. This combined dataset provides just under <strong>20,000</strong> individual biographical entries. In line with data protection recommendations, all class portraits and biographical entries up to and including 1945 are available via the website\'s database (48 <a href="../classpieces">class portraits</a> and approximately <strong>14,000</strong> entries).</div>\n<div> </div>\n</div>\n<div>\n<p>September 2020 marked the beginning of Phase II of the Clericus Project. Over the following months the project expanded its database on the Irish clerical population and digital preservation initiative through collaboration with several new institutions. The project first sought to expand the database’s existing information on clerical students through the addition of biographical data relating to the ministry of a subset of the clerical population based in the Diocese of Meath.The Clericus team extracted relevant data from the well-known and recently updated <a href="../resource/55466"><em>History of the Diocese of Meath, 1860-1993</em></a>. In total, over <strong>750</strong> new biographical entries were created for the period 1690 to 1941.</p>\n<p>Apart from deepening our understanding of individual career paths and networks, this work package permitted the project to further test, develop and showcase the database’s dynamic qualities through the integration and synergy of data from several heterogeneous sources. This, in turn, offered the practical experience and customised system necessary to handle a range of new sources and data during future stages of the project. </p>\n<p>Following the successful completion of the Meath work package, Clericus expanded its spatial/geographical range by focusing on the international dimension of the Irish Catholic Church and its clergy. This came in the form of a collaborative project with the Irish Cultural Centre, Paris and members of the academic research community. The project was kindly provided with a dataset compiled by Dr Liam Chambers and Dr Sarah Franks on the student population of the <a href="../resource/63451">Irish College Paris (ICP)</a>. This dataset was compiled using student records from the college’s archives (available <a href="https://archives-en.centreculturelirlandais.com/archives-en">here</a>), and included over <strong>2,000</strong> student entries covering the period 1832 up to the college’s evacuation at the outbreak of World War II. This represents a rich source of information regarding the biographies of individual students, such as information relating to dates of birth, baptism, confirmation, subjects studied and other observations. The value of the data to members of the public researching their family history is increased due to the inclusion of parents\' names (including maiden names) for over half of the students. Almost <strong>200</strong> ICP students would also spend time studying at St Patrick\'s College Maynooth (SPCM), which in turn deepens our understanding of individual formation and career paths. One excellent example to highlight this enrichment process is seen in <a href="9027">Kevin Clark</a> of Meath diocese, whose database entry draws on information from every resource utilised within the Clericus system up until that point.</p>\n<p>The second phase also saw the project expand its temporal range to include data from the early modern period. Several of the most comprehensive records for Ireland’s seventeenth- and eighteenth-century Catholic clergy were identified. As part of this process, the Clericus team recently completed the ingestion of over <strong>1,500</strong> new biographical entries relating to Irish clerical students from the Universities of Paris and Toulouse during the period 1573 to 1792. This data is drawn from the impressive prosopography on the Irish student community created by <a href="../resource/86488">L. W. B. Brockliss and Patrick Ferté</a>. Many of these students were tied to the Irish College Paris (ICP), and the ingestion of this data expands our database to include a large percentage of the individuals who attended the seminary college across the almost four centuries of its existence. Completing this work package has provided the Clericus team with the experience and knowledge necessary to undertake similar work packages on the numerous other Irish colleges active on the continent during the early modern and modern periods. This includes ongoing work being carried out on the ordinations of Irish students in Lisbon and oaths taken by the student body of the Irish College Salamanca. Part of this process has also involved work on a data template to help standrdise and streamline the ingestion of data into the Clericus database.</p>\n<p>No research on the early modern clergy would be complete without having covered Ireland\'s penal laws. Our understanding of the impact of these restrictions on the Catholic Church has advanced greatly over the last fifty years or so. However, the number and identities of the Catholic clergy active on the Irish mission during the ‘Long eighteenth century’ remains unclear. One aim of the Clericus project has been to help fill this lacuna in our knowledge by compiling the first comprehensive database on this population. The Clericus system is ideally suited to completing this important task, while the dynamic nature of our system and data model permits us to identify, capture and chart the social and professional networks, both clerical and lay, that these individuals maintained across Ireland and the continent. This will add layers of complexity and nuance to our data and subsequent understanding of the worlds navigated by thousands, if not tens of thousands of these individuals. </p>\n<p>The first building block of this monumental undertaking was a dataset compiled from the <a href="../article/irelands-popish-parish-priest-in-1704-">1704 clergy registration</a>. Access to a rare copy of this document was kindly provided to the Clericus team by the archivists of The Honourable Society of King’s Inn, Dublin. The registration of Ireland’s ‘Popish Parish Priests’ in 1704 represents one of the most valuable records concerning the island’s eighteenth-century Catholic clergy – the document covers the entire country for one year and provides relatively detailed information on each cleric. This includes their name, place of abode, parish(es), date of ordination, where they received orders, from whom (i.e. bishop) and two lay individuals acting as sureties or guarantors for each priest. In total, the document lists <strong>1,089</strong> priests, just over <strong>800</strong> lay sureties and several dozen Irish and foreign bishops. Carrying out this work package made it necessary to expand the number of organisations (i.e. townlands, parishes and dioceses) and spatial locations within the Clericus system, including many examples found outside of Ireland. This process also led to the further development of the system’s taxonomy, with the number of event types and relation types in particular having grown to meet the demands imposed by such a sizeable and complex dataset.</p>\n<p>Following the ingestion of this data, work on the Clericus system briefly moved away from large datasets to focus instead on smaller, more numerous resources. The aim behind this was to further enrich individual careers to a degree not yet seen in the database by providing granular biographical data and important network linkages between entries within the system. To achieve this, a selection of documents relating to the clergy of Dublin diocese covering twenty years either side of 1704 was chosen. This included a government census of <a href="../article/sculking-about-the-towne-the-clergy-of-dublin-diocese-in-1698">Dublin’s clergy in 1698</a>, a <a href="../article/lobbying-and-last-wills-and-testaments">testimony and will</a> relating to Bishop <a href="77739">John Dempsey</a> from 1693 and 1703 respectively and a second will from c.1728 belonging to an associated cleric, <a href="76511">Dominic Edward Murphy</a>. The work carried out enriching their biographical entries has provided the testbed and framework necessary to undertake similar work packages relating to other biographical entries already present in the Clericus system. </p>\n<p>Earlier this year the Clericus team was joined by Dr Ciaran Reilly as part of a project that seeks to utilise the <a href="../article/obituaries-as-a-source-for-clericus-">obituaries</a> of Maynooth educated priests as a source of information to help further enrich biographical entries contained within the database. To date over <strong>350</strong> obituaries have been identified from c.1860-1900 which relate to clerics already entered in the Clericus database. While this is admittedly a small sample, the obituaries as a source are quite revealing. These obituaries allow the potential to further expand the dataset and establish networks based on associational culture and/or familial connections. In addition, similar biographical information is also present in month’s mind notices, notices of charitable bequests and others reports, but these are not as common as obituaries. From an international perspective, these obituaries provide important information on clerics who ministered in the <a href="../article/maynooth-clerics-in-st-louis">USA</a>, Canada, Australia and New Zealand, revealing the key roles such individuals played in establishing the Catholic Church in these countries.</p>\n<p>Finally, between October and December of this year, the Clericus project will once again turn its focus to the student population of an Irish seminary. With the assistance of a Kevin B. Nolan Digitisation Grant from the Royal Irish Academy (RIA), the Clericus team will capture and ingest student data and class portraits belonging to St. Kieran’s College, Kilkenny. Between 1793 and 1994, St. Kieran’s acted as one of Ireland’s nine diocesan seminaries and educated several thousand clerical students over the course of two centuries. Of the estimated <strong>2,000</strong> who were ultimately ordained for the priesthood, almost two-thirds were dispatched to missions in the United States, Great Britain, Australia and various other countries. Furthermore, this digitisation initiative will also provide members of the Irish public and diaspora with an accessible and interactive digital platform through which to undertake genealogical research.</p>\n<p>To read more about the project and its content, please see the \'<a href="../article-category/articles">Articles</a>\' section on the Clericus website. Alternatively, visitors to the website can view recent news items on our homepage and/or read about specific priests under \'Highlights\'.</p>\n<p> </p>\n<p>The project\'s team are:</p>\n<p>Prof Thomas O\'Connor, Principal Investigator</p>\n<p>Stavros Angelis, Chief Technical Officer</p>\n<p>Dr Ciaran Reilly, Research Assistant</p>\n<p>Dr Richard Fitzpatrick, Research Assistant &amp; Content Manager </p>\n<p>September 2021</p>\n</div>',
    teaser:
      "<div>\n<p>Clericus is a digital humanities research project that aims to develop a database on the Irish clerical population for the early modern and modern periods. Phase I of the project, financed by St. Patrick's College Maynooth (SPCM), focused on the students and faculty of St. Patrick's College, historically Ireland's largest seminary and pontifical university. The principal sources used were class portraits and student lists. Phase II of the project seeks to expand the Clericus database through the addition of new datasets from various sources dating as far back as the sixteenth century.</p>\n</div>\n<div>\n<p> </p>\n</div>",
    status: 'public',
    featuredImage: '43963',
    featuredImageDetails: {
      _id: '43963',
      filename: 'cos-logo-bw.jpg',
      type: 'image',
      year: 2020,
      month: 6,
      hashedName: 'af426e8dcbc3255968c893dd892898d3.jpg',
      paths: [
        {
          path: 'http://localhost:5100/uploads/2020/6/images/af426e8dcbc3255968c893dd892898d3.jpg',
          pathType: 'source',
        },
        {
          path: 'http://localhost:5100/uploads/2020/6/thumbnails/af426e8dcbc3255968c893dd892898d3.jpg',
          pathType: 'thumbnail',
        },
      ],
      createdBy: '432',
      createdAt: '2020-06-24T11:02:24.964Z',
      updatedBy: '432',
      updatedAt: '2020-06-24T11:02:24.964Z',
      label: 'undefined',
    },
    author: 'Admin',
    createdBy: '432',
    createdAt: '2020-06-15T10:35:32.899Z',
    updatedBy: '532',
    updatedAt: '2021-10-08T09:18:25.163Z',
    highlight: false,
    highlightOrder: 0,
    categories: [
      {
        _id: '24990',
        label: 'About',
        permalink: 'about',
        parentId: 0,
        status: 'public',
        createdBy: '432',
        createdAt: '2020-07-06T11:02:58.806Z',
        updatedBy: '432',
        updatedAt: '2020-07-06T11:02:58.806Z',
      },
    ],
  },
  error: [],
  msg: 'Query results',
};

export const highlights = {
  status: true,
  data: [
    {
      updatedBy: '72756',
      label: 'Peter Yorke ',
      content:
        '<p><strong>Peter Yorke (1864-1925): A Maynooth priest in San Francisco</strong></p>\n<p>In 1949 in a series of radio lectures for Radio Eireann, the Bishop of Galway, Most Rev Dr Browne provided an overview on the careers of famous Maynooth clerics. One such person who featured in these lectures was <a href="../person/30124"><strong>Peter Yorke</strong></a>, a Galway man who led a successful struggle against anti-Catholicism and anti-trade unionism in San Francisco in the 1890s.</p>\n<p>The son of Gregory Yorke, a sea captain who owned several ships which traded between Galway and Newfoundland, and Bridget Kelly of Clew Bay, Yorke entered Maynooth in 1882 and in 1887. In Yorke\'s class were Edward Mulhern of Dromore; John Begley of Limerick; Eugene O’Growney and Denis Flynn of Meath, and Patrick Keown of Clogher, names which Bishop Browne claimed later won renown.</p>\n<p>After his appointment to the Cathedral Parish of San Francisco, Yorke came to prominence in journalism at a time when a secret society called the American Protective Association carried out violent propaganda against the Catholic Church. In 1901 when a great dispute broke out between haulage workers and employers in San Francisco Yorke championed the workers cause and fought for their rights.</p>\n<p>Editor of a number of newspapers including <em>The Monitor </em> and <em>The </em>Leader, Yorke was also a supporter of the Gaelic League and Sinn Fein. In 1899 he gave a lecture in Dublin entitled ‘The Turning of the Tide’ which was said to have been an influential moment for Irish nationalists.</p>\n<p>In recalling the career of Fr Yorke who died in 1925, the Bishop of Galway remembered a great ‘preacher, writer, and author’ concluding ‘we salute the thousands of Maynooth priests who in many lands devoted all their energies and talents to the same great cause’</p>\n<p>Today, a street in San Francisco, Peter Yorke Way, is named in his honour.</p>\n<p> </p>',
      createdAt: '2021-08-02T21:35:43.486Z',
      highlight: true,
      highlightOrder: '1',
      createdBy: '72756',
      featuredImage: '86594',
      _id: '86589',
      category: [24468, 73686],
      permalink: 'peter-yorke-',
      status: 'public',
      teaser: '',
      updatedAt: '2021-08-10T09:33:38.746Z',
      systemLabels: ['Article'],
      featuredImageDetails: {
        _id: '86594',
        filename: 'PeterCYorke.jpg',
        type: 'image',
        year: 2021,
        month: 8,
        hashedName: '323d860e6b2ff01756b5b0254cf8a10b.jpg',
        paths: [
          {
            path: 'http://localhost:5100/uploads/2021/8/images/323d860e6b2ff01756b5b0254cf8a10b.jpg',
            pathType: 'source',
          },
          {
            path: 'http://localhost:5100/uploads/2021/8/thumbnails/323d860e6b2ff01756b5b0254cf8a10b.jpg',
            pathType: 'thumbnail',
          },
        ],
        createdBy: '72756',
        createdAt: '2021-08-02T22:02:34.358Z',
        updatedBy: '72756',
        updatedAt: '2021-08-02T22:02:34.358Z',
        label: 'undefined',
      },
      author: 'Ciaran Reilly',
    },
    {
      updatedBy: '72756',
      label: 'John Harty',
      content:
        '<p><strong><a href="../person/36583">Rev John Harty</a></strong> entered St Patrick’s College, Maynooth in August 1867 and was ordained on 21 June 1874. Afterwards, Harty was appointed to St Patrick’s Church, Providence, Rhode Island. At the Sacred Heart Church in East Providence, Harty greatly reduced the church debt; built the handsome St Margaret’s Church in Rumford and in early 1897 he was appointed to the Church of the Sacred Heart in Pawtucket. Harty also held the office of State chaplain to the Knights of Columbanus.</p>',
      createdAt: '2021-07-09T00:06:26.502Z',
      highlight: true,
      highlightOrder: '2',
      createdBy: '72756',
      featuredImage: '86495',
      _id: '24416',
      permalink: 'john-harty',
      category: [24468],
      status: 'public',
      teaser: '',
      updatedAt: '2021-08-10T09:33:05.894Z',
      systemLabels: ['Article'],
      featuredImageDetails: {
        _id: '86495',
        filename: 'Rev John Harty.png',
        type: 'image',
        year: 2021,
        month: 7,
        hashedName: '26faca99e0248f24bcd660759c13ed0f.png',
        paths: [
          {
            path: 'http://localhost:5100/uploads/2021/7/images/26faca99e0248f24bcd660759c13ed0f.png',
            pathType: 'source',
          },
          {
            path: 'http://localhost:5100/uploads/2021/7/thumbnails/26faca99e0248f24bcd660759c13ed0f.png',
            pathType: 'thumbnail',
          },
        ],
        createdBy: '72756',
        createdAt: '2021-07-09T00:09:35.116Z',
        updatedBy: '72756',
        updatedAt: '2021-07-09T00:09:35.116Z',
        label: 'undefined',
      },
      author: 'Ciaran Reilly',
    },
    {
      updatedBy: '532',
      label: 'Jack P. Hanlon',
      content:
        '<p><a href="../person/8659">John Hanlon</a> (Jack P.) (1913-1968), Dublin diocese, born in Templeogue and educated at Belvedere College before beginning his clerical studies at Clonliffe in 1932 and BA at UCD. Hanlon subsequently transferred to St. Patrick’s College Maynooth in 1934/35 and was ordained in June 1939. </p>\n<p>Having shown considerable artistic talent, Hanlon attended classes in the 1930s given by <a href="../person/87206">Mainie Jellett</a>. His work was first exhibited at the Royal Hibernian Academy (RHA) in 1934 and then at the New York World Fair in 1939. Following his ordination, he travelled to Paris to study under the Cubist painter <a href="../person/87208">André Lhote</a> - probably because of the influence of Jellett, who had studies under Lhote during the 1920s. It was during this period that his traditional style came increasingly under the influence of Modernism; a fact reflected in his role in 1943, alongside Jellett and several other Irish artists, as a founding member of the Irish Exhibition of Living Art (IELA). </p>\n<p>He would continue to exhibit his work regularly over the following decades, including at the Victor Waddington and Dawson galleries in Dublin. His work gained further international exposure through inclusion in the London Olympics Art Section in 1948 (bronze medal), and a subsequent commission to paint a mural for the Irish Pavilion at the Chicago World Fair in 1950. The 1950s and 1960s would see him complete several church commissions in Ireland and abroad, including a set of stations of the cross for the Church of Stella Maris in Downings Co. Donegal (1955), and five painted panels for the Church of the Holy Rosary, Limerick (1958).</p>\n<p>Hanlon was an enthusiastic gardener and he celebrated the beauty of nature in the many still lives of flowers he produced throughout his career. Much of his best work was in watercolour where primary importance was given to light and colour. This emphasis was also seen in his oil paintings. There was a delicacy to his palette dominated by pastel shades as well as strong primary colours, which he applied in blocks of flat colour and highlights his cubist influences. This mix of vibrancy and delicacy in his work stands in stark contrast to the much more restrained and austere nature of 1940s and 1950s Irish society.</p>\n<p>From 1945, Hanlon served as curate for several Wicklow parishes, a position that permitted him to focus more time and energy on his art. Hanlon remained a curate until illness forced him to retire to Sandycove in 1967. In August 1968 he was taken seriously ill in Tullamore, Co. Offaly and was transferred to Jervis Street Hospital where he underwent surgery, possibly for a burst appendix. He died 12 August 1968, aged 55, and was buried alongside his parents in Templeogue cemetery, Dublin.</p>\n<p>Examples of Jack P. Hanlon\'s work can be found <a href="https://www.whytes.ie/artist/father-jack-p-hanlon/15296/">here</a>.</p>\n<p><strong>Sources:</strong></p>\n<p>John Coleman, ‘A painter of living art: Jack P. Hanlon 1913-1968’ in <em>The GPA Irish Arts Review Yearbook</em> (1988), pp 222-228.</p>\n<p>Mary Catherine Reilly, ‘Hanlon, Jack P. (John Thomas)’ in <em>Dictionary of Irish Biography</em>, available <a href="https://www.dib.ie/biography/hanlon-jack-p-john-thomas-a3782%20">here</a></p>\n<p>‘Jack P. Hanlon (Irish Artist Directory)’ in <em>Adam’s Auctioneers</em>, available <a href="https://www.adams.ie/irish-artist-directory/jack-p.-hanlon-art-sold-at-auction">here</a></p>\n<p>September 2021</p>\n<p> </p>',
      createdAt: '2021-09-16T13:17:34.821Z',
      highlight: true,
      highlightOrder: '3',
      featuredImage: '87242',
      createdBy: '532',
      _id: '87240',
      category: [73686, 24468, 872],
      permalink: 'jack-p-hanlon',
      status: 'public',
      teaser: '<p>Modernist artist</p>',
      updatedAt: '2021-09-16T13:51:39.616Z',
      systemLabels: ['Article'],
      featuredImageDetails: {
        _id: '87242',
        filename: 'Jack P. Hanlon image.jpg',
        type: 'image',
        year: 2021,
        month: 9,
        hashedName: '67faec04c7d5316670ffdcf7f0c35d1c.jpg',
        paths: [
          {
            path: 'http://localhost:5100/uploads/2021/9/images/67faec04c7d5316670ffdcf7f0c35d1c.jpg',
            pathType: 'source',
          },
          {
            path: 'http://localhost:5100/uploads/2021/9/thumbnails/67faec04c7d5316670ffdcf7f0c35d1c.jpg',
            pathType: 'thumbnail',
          },
        ],
        createdBy: '532',
        createdAt: '2021-09-16T13:24:40.527Z',
        updatedBy: '532',
        updatedAt: '2021-09-16T13:24:40.527Z',
        label: 'undefined',
      },
      author: 'Richard Fitzpatrick',
    },
    {
      updatedBy: '532',
      label: 'Fr. John Blowick',
      content:
        '<p><a href="../person/11598">John Blowick</a> (1888-1972), Tuam diocese, born at Belcarra, Co. Mayo and educated at St. Jarlath’s College, Tuam, where he was described as ‘a good looking boy, thin, frail, self-possessed, with a kind encouraging word for new comers’. He entered St. Patrick’s College Maynooth in 1906 and was ordained in 1913. Blowick understood postgraduate studies at Maynooth in 1914, and while still a student he had the rare distinction of winning, in a public concursus, the chair of Dogmatic Theology in Maynooth (he was the last Maynooth professor selected in that way).</p>\n<p>Several years earlier, in June 1911, Blowick heard a lecture on China by the Canadian missionary, Fr. Fraser, which made a lasting impression on him. In 1916 he met <a href="../person/12150">Edward Galvin</a> and subsequently resigned his chair as professor of theology to assist Galvin in establishing a missionary society. Formal permission for the Maynooth Mission to China was given soon after by Cardinal <a href="../person/39532">Michael Logue</a> and the Archbishop of Dublin, Dr <a href="../person/8101">William Walsh</a>, with the former stating on the occasion ‘It is a consoling thing, for men whose work is almost done, to see young priests go forward willingly in such a grand work, and without having the Bishops after them with the pitchforks. I thank God that the missionary spirit is still alive’. By the time of its formal papal recognition in 1918, the society had taken on its lasting title of the <a href="../organisation/3923">Society of St. Columban</a>.</p>\n<p>Fr. Blowick remained a central figure within the society, being elected Superior General in 1919 and was amongst the first group of Columbans to travel to China in 1920 to begin their missionary work. Before travelling to China, however, Blowick had given a talk about the great need for dedicated women who would serve with the priests in ministering to the needs of the poor in China. In the audience that day was Frances Moloney, a young widow involved in efforts to relieve the poor of Dublin City. Thus, in 1922, Fr. Blowick and Moloney co-founded the Missionary Sisters of St. Columban. </p>\n<p>One of the earliest members of the missionary sisters, Patricia Sweeney, would describe Fr. Blowick as ‘a man of great missionary zeal. Yet, as we meet him in those early days we do not find him carried away in any impetuous manner by this zeal. The development of his missionary vocation and his response to the action of the Holy Spirit seem to have tempered what, to priests and students who knew him well, was a naturally impulsive character. In this new phrase of his vocational response we find a clear-thinking, far-seeing, cautious yet enthusiastic shaper of a mission. Mission needs were studied and, by systemic effort, real needs were given priority’. A letter from 1918 sums up Blowick’s approach: ‘Everything depends on initiative, and prudence to a certain point, but not too much – too much prudence will keep us from doing anything.’</p>\n<p>Returning to the Columbans, Blowick was elected Vicar-General and appointed Director in Ireland in 1924. He was again elected to the Superior General’s Council in 1947 and taught theology at the society\'s new seminary at Dalgan Park near Navan, Co. Meath. When he was in his seventies Fr. Blowick undertook a journey that took him to the principal missions of the Society. Following his death in 1972, Fr. Blowick was interred at Dalgan Park.</p>\n<p>For information on other Maynooth educated members of the society, see <a href="../resource/94486">here</a></p>\n<p> </p>\n<p><strong>Sources:</strong></p>\n<p>Neil Collins (ed.), <em>Those who journey with us: deceased Columbans, 1918-2016</em>, available <a href="http://disa-app02.sixfeetup.com:8091/columban/documents/those-who-journeyed-with-us-to-2016.pdf">here</a></p>\n<p>Tom Murphy, \'Dalgan Park: Columban Missions\', available <a href="http://www.shrule.com/?page_id=1760">here</a></p>\n<p>\'Fr John Blowick\' in <em>Missionary Sisters of St. Columban</em>, available <a href="https://www.columbansisters.org/fr-john-blowick/">here</a></p>\n<p> </p>\n<p>October 2021</p>',
      createdAt: '2021-10-15T18:55:08.397Z',
      highlight: true,
      highlightOrder: '4',
      createdBy: '532',
      featuredImage: '94508',
      _id: '94507',
      permalink: 'fr-john-blowick',
      category: [24468, 872, 73686],
      status: 'public',
      teaser:
        '<p>Co-founder of the Society of St. Columban and the Missionary Sisters of St. Columban</p>',
      updatedAt: '2021-10-20T17:18:23.749Z',
      systemLabels: ['Article'],
      featuredImageDetails: {
        _id: '94508',
        filename: 'John Blowick.jpg',
        type: 'image',
        year: 2021,
        month: 10,
        hashedName: 'bb0925ba1ab78bd3ea945e04c1907acb.jpg',
        paths: [
          {
            path: 'http://localhost:5100/uploads/2021/10/images/bb0925ba1ab78bd3ea945e04c1907acb.jpg',
            pathType: 'source',
          },
          {
            path: 'http://localhost:5100/uploads/2021/10/thumbnails/bb0925ba1ab78bd3ea945e04c1907acb.jpg',
            pathType: 'thumbnail',
          },
        ],
        createdBy: '532',
        createdAt: '2021-10-15T18:59:13.072Z',
        updatedBy: '532',
        updatedAt: '2021-10-15T18:59:13.072Z',
        label: 'undefined',
      },
      author: 'Richard Fitzpatrick',
    },
    {
      updatedBy: '531',
      label: 'Andrew Eustace',
      content:
        '<p><strong>Rev <a href="../person/33716">Andrew Eustace </a></strong>(1833-1893) was born in Dublin and educated at Castleknock College and St Patrick\'s College, Maynooth where he matriculated into Logic in 1849. In October 1854, Eustace went to America where he studied at Carondolet Seminary in St. Louis, Missouri. Rev <a href="../person/34238">P<strong>atrick Feehan</strong>,</a>later Archbishop of Chicago and with whom Eustace had studied with at Maynooth, was then president of Carondolet Seminary. Serving in Chicago and St Louis, Eustace died a week before his 60th birthday in 1893. He was a cousin of Archbishop <strong><a href="../person/38619">Peter Kenrick</a></strong>  of St Louis, Missouri, who also studied at St Patrick’s College, Maynooth. </p>',
      createdAt: '2021-07-08T11:03:52.936Z',
      highlight: true,
      highlightOrder: '5',
      featuredImage: '86451',
      createdBy: '72756',
      _id: '86496',
      category: [24468],
      permalink: 'andrew-eustace',
      status: 'public',
      teaser: '',
      updatedAt: '2021-08-24T11:08:24.710Z',
      systemLabels: ['Article'],
      featuredImageDetails: {
        _id: '86451',
        filename: 'andrew1.jpg',
        type: 'image',
        year: 2021,
        month: 7,
        hashedName: '215edfa7812d6c6041c515a75a6426e1.jpg',
        paths: [
          {
            path: 'http://localhost:5100/uploads/2021/7/images/215edfa7812d6c6041c515a75a6426e1.jpg',
            pathType: 'source',
          },
          {
            path: 'http://localhost:5100/uploads/2021/7/thumbnails/215edfa7812d6c6041c515a75a6426e1.jpg',
            pathType: 'thumbnail',
          },
        ],
        createdBy: '72756',
        createdAt: '2021-07-08T22:58:08.329Z',
        updatedBy: '72756',
        updatedAt: '2021-07-08T22:58:08.329Z',
        label: 'undefined',
      },
      author: 'Ciaran Reilly',
    },
    {
      updatedBy: '72756',
      label: 'John Bannon ',
      content:
        '<h6><a href="../person/23897">John Bannon  </a>(1829-1913) Dublin diocese but born at Rooskey, county Roscommon entered St Patrick\'s College, Maynooth in 1847 and was ordained as Deacon in 1853. Sent to the archdiocese of St Louis, Missouri in the same year, where he won praise for his work. When the US Civil War broke out Bannon joined the Confederate army and was attached to the Missouri light artillery. Present at a number of battles, Bannon accompanied his unit through northern Mississippi in 1862–1863. Although taken prisoner after the Confederate defeat at Vicksburg, Bannon was soon released and travelled to Richmond where he was asked by Jefferson Davis to undertake a mission to Ireland to discourage recruitment for the Federal forces. Throughout 1864 he wrote to the <em>Nation newspaper </em>and toured the country giving political lectures. Following the end of the war Bannon entered the Jesuit novitiate at Miltown Park, Dublin (1865–6), and later studied at Louvain.  In 1867–70 he travelled Ireland as part of the Jesuit team of missionary preachers. Thereafter he founded several sodalities in Dublin. Bannon was superior of the Jesuit community in Upper Gardiner Street, Dublin (1883–9), where he spent the remainder of his life. He died 14 July 1913 at the Jesuit residence in Upper Gardiner Street and was buried in the Jesuit plot at Glasnevin cemetery.</h6>\n<h6>Courtesy of the <a href="https://www.jesuitarchives.ie/">Irish Jesuit Archives</a></h6>',
      createdAt: '2021-06-22T10:31:22.125Z',
      highlight: true,
      highlightOrder: '6',
      featuredImage: '86163',
      createdBy: '72756',
      _id: '86159',
      permalink: 'john-bannon-',
      category: [24468],
      status: 'public',
      teaser: '',
      updatedAt: '2021-08-10T09:34:31.008Z',
      systemLabels: ['Article'],
      featuredImageDetails: {
        _id: '86163',
        filename: 'John Bannon 2.jpg',
        type: 'image',
        year: 2021,
        month: 6,
        hashedName: '7fef458a62ff9affa1537f8d4e1efce0.jpg',
        paths: [
          {
            path: 'http://localhost:5100/uploads/2021/6/images/7fef458a62ff9affa1537f8d4e1efce0.jpg',
            pathType: 'source',
          },
          {
            path: 'http://localhost:5100/uploads/2021/6/thumbnails/7fef458a62ff9affa1537f8d4e1efce0.jpg',
            pathType: 'thumbnail',
          },
        ],
        createdBy: '532',
        createdAt: '2021-06-22T10:55:15.248Z',
        updatedBy: '532',
        updatedAt: '2021-06-22T10:55:15.248Z',
        label: 'undefined',
      },
      author: 'Ciaran Reilly',
    },
    {
      updatedBy: '72756',
      label: 'Daniel Cahill',
      content:
        '<p><strong><a href="../person/21328">Rev Daniel Cahill</a> </strong>(1796-1864) was born in Queen’s County (now Laois). Educated at Carlow College, Cahill entered St Patrick’s College, Maynooth in 1816. Having completed his studies in Maynooth, in 1825 he was appointed Professor of Natural Philosophy at Carlow College. Cahill was a proficient writer and edited the <em>Dublin Telegraph</em>. He was also a distinguished lecturer and a vocal opponent of the British government. In 1859 he went to the USA and lectured on Astronomy and other scientific subjects, and preached in many American and Canadian cities. He died in Boston in 1864 but his body was exhumed in 1885 and taken to Ireland, where it was buried in Glasnevin Cemetery, Dublin. His writings, entitled <em>Life, Letters, and Lectures of Rev. Dr. Cahill</em> was published in 1886.</p>',
      createdAt: '2021-07-09T20:06:12.027Z',
      highlight: true,
      highlightOrder: '9',
      featuredImage: '86586',
      createdBy: '72756',
      _id: '4491',
      category: [24468],
      permalink: 'daniel-cahill',
      status: 'public',
      teaser: '',
      updatedAt: '2021-07-29T22:07:21.602Z',
      systemLabels: ['Article'],
      featuredImageDetails: {
        _id: '86586',
        filename: 'Daniel Cahill.png',
        type: 'image',
        year: 2021,
        month: 7,
        hashedName: '680a87627f2e998d96fcf3af3afb899f.png',
        paths: [
          {
            path: 'http://localhost:5100/uploads/2021/7/images/680a87627f2e998d96fcf3af3afb899f.png',
            pathType: 'source',
          },
          {
            path: 'http://localhost:5100/uploads/2021/7/thumbnails/680a87627f2e998d96fcf3af3afb899f.png',
            pathType: 'thumbnail',
          },
        ],
        createdBy: '72756',
        createdAt: '2021-07-29T22:07:02.398Z',
        updatedBy: '72756',
        updatedAt: '2021-07-29T22:07:02.398Z',
        label: 'undefined',
      },
      author: 'Ciaran Reilly',
    },
    {
      updatedBy: '72756',
      label: "Daniel O'Sullivan ",
      content:
        '<p><a href="../person/6295">Daniel O’Sullivan</a> (Dómhnall O Suilleabháin)  Kerry diocese, entered St Patrick’s College, Maynooth in 1907 and was ordained in 1914. A son of Dan and Hannah O\'Sullivan of High Street, Killarney, county Kerry, following ordination O’Sullivan was sent to work at St Brendan\'s Seminary where he had been educated himself. Following a call from the Bishop of Kerry, <a href="../person/42868">John Mangan</a> for a chaplain to serve the men from the diocese who had enlisted in British war effort, O’Sullivan answered the call.</p>\n<p>On 5 July 1916, just five days after the start of the infamous Battle of the Somme, O’Sullivan was killed by shrapnel while ministering to a wounded soldier. A poem in his memory was published the following week in the <em>Kerry News</em>:</p>\n<p> </p>\n<p><strong>In Memoriam</strong></p>\n<p>Captain Donal O’Sullivan chaplain to the Forces. Born in Killarney. Educated at Maynooth. Killed in France, July 1916.</p>\n<p><em>The laughter of the little days gone by. The memory of some unforgotten smile, with priestly blood spilt on the altar steps are hard to reconcile. </em></p>\n<p><em>From converse with his comrades of the school, from words of home and the caress of friends, who dreamed the Lord would snatch away so soon, an Isaac for his ends.</em></p>\n<p><em>Yet rest content, ye cloisters of Maynooth. Smile gently o’er Killarney, summer sun, for God who called to swift reward and true, first saw his work well done. </em></p>\n<p><em>And ye who nearest to the undying dead, must weep o’er vacant chair and shattered shrine, be sure that God behind this cloud doth veil, some sure august design. </em></p>\n<p><strong>L.F.K.</strong></p>',
      createdAt: '2021-06-23T16:36:49.907Z',
      highlight: true,
      highlightOrder: '10',
      featuredImage: '86452',
      createdBy: '72756',
      _id: '86246',
      permalink: 'daniel-osullivan-',
      category: [24468],
      status: 'public',
      teaser: '',
      updatedAt: '2021-07-08T23:03:06.800Z',
      systemLabels: ['Article'],
      featuredImageDetails: {
        _id: '86452',
        filename: 'Daniel O Sullivan .png',
        type: 'image',
        year: 2021,
        month: 7,
        hashedName: 'd1b8f6b77c3477bcb8a887f7e4092aba.png',
        paths: [
          {
            path: 'http://localhost:5100/uploads/2021/7/images/d1b8f6b77c3477bcb8a887f7e4092aba.png',
            pathType: 'source',
          },
          {
            path: 'http://localhost:5100/uploads/2021/7/thumbnails/d1b8f6b77c3477bcb8a887f7e4092aba.png',
            pathType: 'thumbnail',
          },
        ],
        createdBy: '72756',
        createdAt: '2021-07-08T23:02:56.533Z',
        updatedBy: '72756',
        updatedAt: '2021-07-08T23:02:56.533Z',
        label: 'undefined',
      },
      author: 'Ciaran Reilly',
    },
  ],
  error: [],
  msg: 'Query results',
};

export const news = {
  status: true,
  data: {
    currentPage: 1,
    data: [
      {
        updatedBy: '532',
        label: 'Fr. John Blowick',
        content:
          '<p><a href="../person/11598">John Blowick</a> (1888-1972), Tuam diocese, born at Belcarra, Co. Mayo and educated at St. Jarlath’s College, Tuam, where he was described as ‘a good looking boy, thin, frail, self-possessed, with a kind encouraging word for new comers’. He entered St. Patrick’s College Maynooth in 1906 and was ordained in 1913. Blowick understood postgraduate studies at Maynooth in 1914, and while still a student he had the rare distinction of winning, in a public concursus, the chair of Dogmatic Theology in Maynooth (he was the last Maynooth professor selected in that way).</p>\n<p>Several years earlier, in June 1911, Blowick heard a lecture on China by the Canadian missionary, Fr. Fraser, which made a lasting impression on him. In 1916 he met <a href="../person/12150">Edward Galvin</a> and subsequently resigned his chair as professor of theology to assist Galvin in establishing a missionary society. Formal permission for the Maynooth Mission to China was given soon after by Cardinal <a href="../person/39532">Michael Logue</a> and the Archbishop of Dublin, Dr <a href="../person/8101">William Walsh</a>, with the former stating on the occasion ‘It is a consoling thing, for men whose work is almost done, to see young priests go forward willingly in such a grand work, and without having the Bishops after them with the pitchforks. I thank God that the missionary spirit is still alive’. By the time of its formal papal recognition in 1918, the society had taken on its lasting title of the <a href="../organisation/3923">Society of St. Columban</a>.</p>\n<p>Fr. Blowick remained a central figure within the society, being elected Superior General in 1919 and was amongst the first group of Columbans to travel to China in 1920 to begin their missionary work. Before travelling to China, however, Blowick had given a talk about the great need for dedicated women who would serve with the priests in ministering to the needs of the poor in China. In the audience that day was Frances Moloney, a young widow involved in efforts to relieve the poor of Dublin City. Thus, in 1922, Fr. Blowick and Moloney co-founded the Missionary Sisters of St. Columban. </p>\n<p>One of the earliest members of the missionary sisters, Patricia Sweeney, would describe Fr. Blowick as ‘a man of great missionary zeal. Yet, as we meet him in those early days we do not find him carried away in any impetuous manner by this zeal. The development of his missionary vocation and his response to the action of the Holy Spirit seem to have tempered what, to priests and students who knew him well, was a naturally impulsive character. In this new phrase of his vocational response we find a clear-thinking, far-seeing, cautious yet enthusiastic shaper of a mission. Mission needs were studied and, by systemic effort, real needs were given priority’. A letter from 1918 sums up Blowick’s approach: ‘Everything depends on initiative, and prudence to a certain point, but not too much – too much prudence will keep us from doing anything.’</p>\n<p>Returning to the Columbans, Blowick was elected Vicar-General and appointed Director in Ireland in 1924. He was again elected to the Superior General’s Council in 1947 and taught theology at the society\'s new seminary at Dalgan Park near Navan, Co. Meath. When he was in his seventies Fr. Blowick undertook a journey that took him to the principal missions of the Society. Following his death in 1972, Fr. Blowick was interred at Dalgan Park.</p>\n<p>For information on other Maynooth educated members of the society, see <a href="../resource/94486">here</a></p>\n<p> </p>\n<p><strong>Sources:</strong></p>\n<p>Neil Collins (ed.), <em>Those who journey with us: deceased Columbans, 1918-2016</em>, available <a href="http://disa-app02.sixfeetup.com:8091/columban/documents/those-who-journeyed-with-us-to-2016.pdf">here</a></p>\n<p>Tom Murphy, \'Dalgan Park: Columban Missions\', available <a href="http://www.shrule.com/?page_id=1760">here</a></p>\n<p>\'Fr John Blowick\' in <em>Missionary Sisters of St. Columban</em>, available <a href="https://www.columbansisters.org/fr-john-blowick/">here</a></p>\n<p> </p>\n<p>October 2021</p>',
        createdAt: '2021-10-15T18:55:08.397Z',
        highlight: true,
        highlightOrder: '4',
        createdBy: '532',
        featuredImage: '94508',
        _id: '94507',
        permalink: 'fr-john-blowick',
        category: [24468, 872, 73686],
        status: 'public',
        teaser:
          '<p>Co-founder of the Society of St. Columban and the Missionary Sisters of St. Columban</p>',
        updatedAt: '2021-10-20T17:18:23.749Z',
        systemLabels: ['Article'],
        featuredImageDetails: {
          _id: '94508',
          filename: 'John Blowick.jpg',
          type: 'image',
          year: 2021,
          month: 10,
          hashedName: 'bb0925ba1ab78bd3ea945e04c1907acb.jpg',
          paths: [
            {
              path: 'http://localhost:5100/uploads/2021/10/images/bb0925ba1ab78bd3ea945e04c1907acb.jpg',
              pathType: 'source',
            },
            {
              path: 'http://localhost:5100/uploads/2021/10/thumbnails/bb0925ba1ab78bd3ea945e04c1907acb.jpg',
              pathType: 'thumbnail',
            },
          ],
          createdBy: '532',
          createdAt: '2021-10-15T18:59:13.072Z',
          updatedBy: '532',
          updatedAt: '2021-10-15T18:59:13.072Z',
          label: 'undefined',
        },
        author: 'Richard Fitzpatrick',
      },
      {
        updatedBy: '532',
        label:
          'Irish Students in the Universities of Paris and Toulouse, 1573-1792',
        content:
          '<p>The newest biographical entries added to the Clericus database encompass over 1,500 Irish clerics who attended the universities of Paris and Toulouse during the period 1573 to 1792. This dataset is based on the updated 2004 version of <a href="../resource/86488">L. W. B. Brockliss and Patrick Ferté’s Prosopography of Irish clerics</a> who attended these institutions. This extensive list provides information on the education of students drawn from surviving university records, alongside additional biographical data compiled by the authors. The majority of entries (1,166) relate to the University of Paris. Toulouse’s far less complete records provide a further 263 entries, with the remaining data covering several other French universities such as at <a href="../organisation/82672">Rodez</a> and <a href="../organisation/82673">Cahors</a>.</p>\n<p>Apart from adding over 1,500 new entries to the Clericus database, this data has helped to enrich the biographical entries for several dozen individuals already present within the Clericus system, including prominent figures such as Archbishop <a href="81074">Edward Comerford</a> and <a href="76535">Cornelius Nary</a>. Added to this are several hundred individuals who were members and students of the Irish colleges at Paris and Toulouse. The former, after 1685, can be characterised as something of a national college drawing its students from all parts of Ireland, while the community of the latter college was mostly drawn from Munster, Cork in particular. For an overview of the history of the Irish College Paris, see <a href="https://www.centreculturelirlandais.com/content/files/History-CCI-English.pdf">here</a>.</p>\n<p>Other notable entries include <a href="../../person/90269">Modestus McSweeny</a>, a native of Cork and superior of the Irish College Toulouse, who was expelled by the Archbishop of Toulouse in c.1690 for inciting rebellion and disorder. McSweeny was nevertheless re-elected as superior of the Irish College and governed \'like a petty tyrant with the help of the Toulousan Parliament\' until expelled by Louis XIV of France in 1704. One interesting, if not odd example from the Irish College Paris was <a href="../../person/90409">Thady McKeogh</a> of Cashel and Emly diocese who, while serving as canon of Strasbourg in 1739, is said to have \'died after going berserk consequent on drinking tea\'.</p>\n<p>Resources:</p>\n<p>L. W. B. Brockliss and Patrick Ferté (eds), \'Prosopography of Irish Clerics in the Universities of Paris and Toulouse, 1573-1792\' in <em>Archivium Hibernicum</em>, lviii (2004), pp 7-166.</p>\n<p>L. W. B. Brockliss and Patrick Ferté (eds), \'Irish Clerics in France in the Seventeenth and Eighteenth Centuries: A Statistical Study\' in <em>Proceedings of the Royal Irish Academy: Archaeology, Culture, History, Literature</em>, 1987, lxxxviiC (1987), pp 527-572.</p>\n<p>Our sincere thanks also to Dr Liam Chambers for his assistance during the compiling of this dataset.</p>\n<p>September 2021</p>',
        createdAt: '2021-09-24T15:05:40.047Z',
        highlight: false,
        highlightOrder: 0,
        createdBy: '532',
        featuredImage: '55133',
        _id: '94020',
        category: [872, 73686],
        permalink: 'irish-students-of-paris-and-toulouse-15731792',
        status: 'public',
        teaser:
          '<p>Over 1,500 new biographical entries added to the Clericus database.</p>',
        updatedAt: '2021-10-14T17:10:31.399Z',
        systemLabels: ['Article'],
        featuredImageDetails: {
          _id: '55133',
          filename: '1895-6 motif detail 1.jpg',
          type: 'image',
          year: 2020,
          month: 9,
          hashedName: '399f8dca763ca015ff8d7883ca8d47d4.jpg',
          paths: [
            {
              path: 'http://localhost:5100/uploads/2020/9/images/399f8dca763ca015ff8d7883ca8d47d4.jpg',
              pathType: 'source',
            },
            {
              path: 'http://localhost:5100/uploads/2020/9/thumbnails/399f8dca763ca015ff8d7883ca8d47d4.jpg',
              pathType: 'thumbnail',
            },
          ],
          createdBy: '532',
          createdAt: '2020-09-03T13:32:00.334Z',
          updatedBy: '532',
          updatedAt: '2020-09-03T13:32:00.334Z',
          label: 'undefined',
        },
        author: 'Richard Fitzpatrick',
      },
      {
        updatedBy: '532',
        label: 'Jack P. Hanlon',
        content:
          '<p><a href="../person/8659">John Hanlon</a> (Jack P.) (1913-1968), Dublin diocese, born in Templeogue and educated at Belvedere College before beginning his clerical studies at Clonliffe in 1932 and BA at UCD. Hanlon subsequently transferred to St. Patrick’s College Maynooth in 1934/35 and was ordained in June 1939. </p>\n<p>Having shown considerable artistic talent, Hanlon attended classes in the 1930s given by <a href="../person/87206">Mainie Jellett</a>. His work was first exhibited at the Royal Hibernian Academy (RHA) in 1934 and then at the New York World Fair in 1939. Following his ordination, he travelled to Paris to study under the Cubist painter <a href="../person/87208">André Lhote</a> - probably because of the influence of Jellett, who had studies under Lhote during the 1920s. It was during this period that his traditional style came increasingly under the influence of Modernism; a fact reflected in his role in 1943, alongside Jellett and several other Irish artists, as a founding member of the Irish Exhibition of Living Art (IELA). </p>\n<p>He would continue to exhibit his work regularly over the following decades, including at the Victor Waddington and Dawson galleries in Dublin. His work gained further international exposure through inclusion in the London Olympics Art Section in 1948 (bronze medal), and a subsequent commission to paint a mural for the Irish Pavilion at the Chicago World Fair in 1950. The 1950s and 1960s would see him complete several church commissions in Ireland and abroad, including a set of stations of the cross for the Church of Stella Maris in Downings Co. Donegal (1955), and five painted panels for the Church of the Holy Rosary, Limerick (1958).</p>\n<p>Hanlon was an enthusiastic gardener and he celebrated the beauty of nature in the many still lives of flowers he produced throughout his career. Much of his best work was in watercolour where primary importance was given to light and colour. This emphasis was also seen in his oil paintings. There was a delicacy to his palette dominated by pastel shades as well as strong primary colours, which he applied in blocks of flat colour and highlights his cubist influences. This mix of vibrancy and delicacy in his work stands in stark contrast to the much more restrained and austere nature of 1940s and 1950s Irish society.</p>\n<p>From 1945, Hanlon served as curate for several Wicklow parishes, a position that permitted him to focus more time and energy on his art. Hanlon remained a curate until illness forced him to retire to Sandycove in 1967. In August 1968 he was taken seriously ill in Tullamore, Co. Offaly and was transferred to Jervis Street Hospital where he underwent surgery, possibly for a burst appendix. He died 12 August 1968, aged 55, and was buried alongside his parents in Templeogue cemetery, Dublin.</p>\n<p>Examples of Jack P. Hanlon\'s work can be found <a href="https://www.whytes.ie/artist/father-jack-p-hanlon/15296/">here</a>.</p>\n<p><strong>Sources:</strong></p>\n<p>John Coleman, ‘A painter of living art: Jack P. Hanlon 1913-1968’ in <em>The GPA Irish Arts Review Yearbook</em> (1988), pp 222-228.</p>\n<p>Mary Catherine Reilly, ‘Hanlon, Jack P. (John Thomas)’ in <em>Dictionary of Irish Biography</em>, available <a href="https://www.dib.ie/biography/hanlon-jack-p-john-thomas-a3782%20">here</a></p>\n<p>‘Jack P. Hanlon (Irish Artist Directory)’ in <em>Adam’s Auctioneers</em>, available <a href="https://www.adams.ie/irish-artist-directory/jack-p.-hanlon-art-sold-at-auction">here</a></p>\n<p>September 2021</p>\n<p> </p>',
        createdAt: '2021-09-16T13:17:34.821Z',
        highlight: true,
        highlightOrder: '3',
        featuredImage: '87242',
        createdBy: '532',
        _id: '87240',
        category: [73686, 24468, 872],
        permalink: 'jack-p-hanlon',
        status: 'public',
        teaser: '<p>Modernist artist</p>',
        updatedAt: '2021-09-16T13:51:39.616Z',
        systemLabels: ['Article'],
        featuredImageDetails: {
          _id: '87242',
          filename: 'Jack P. Hanlon image.jpg',
          type: 'image',
          year: 2021,
          month: 9,
          hashedName: '67faec04c7d5316670ffdcf7f0c35d1c.jpg',
          paths: [
            {
              path: 'http://localhost:5100/uploads/2021/9/images/67faec04c7d5316670ffdcf7f0c35d1c.jpg',
              pathType: 'source',
            },
            {
              path: 'http://localhost:5100/uploads/2021/9/thumbnails/67faec04c7d5316670ffdcf7f0c35d1c.jpg',
              pathType: 'thumbnail',
            },
          ],
          createdBy: '532',
          createdAt: '2021-09-16T13:24:40.527Z',
          updatedBy: '532',
          updatedAt: '2021-09-16T13:24:40.527Z',
          label: 'undefined',
        },
        author: 'Richard Fitzpatrick',
      },
      {
        updatedBy: '72756',
        label: 'Maynooth clerics in St Louis',
        content:
          '<p>Recently added to the ‘Highlights’ section of the Clericus website were details about the career of  <a href="https://www.clericus.ie/person/23897">John Bannon</a>  and his fascinating role in the American Civil War, as chaplain to the Confederate forces. Likewise, those of<a href="https://www.clericus.ie/person/21328%20"> Daniel Cahill</a>, a noted preacher in the USA, and Andrew Eustace, just one of many ‘Maynooth’ men who ministered in St Louis throughout the nineteenth century.</p>\n<p>With thanks to Rena Schergen (MSLIS, CA, Archivist for the Archdiocese of St. Louis) a number of other clerics from St Patrick’s College, Maynooth (SPCM) have been identified as having served in the American diocese. These include <a href="../person/29375">Myles William Tobin</a> (or Tobyn) of Dublin who participated in matriculation into Humanity in 1851 at SPCM; was later ordained in St. Louis and was, for a period, pastor of SS Mary and Joseph’s church in Carondelet.</p>\n<p><a href="https://www.clericus.ie/person/23651">Thomas </a><a href="https://www.clericus.ie/person/23651">Butler</a> (1837-1897) was another of the Maynooth clerics who went to St Louis in the mid-nineteenth century and where it seems  he continued to be outspoken in his support of the Fenian movement in Ireland.  Butler died in 1897 and is buried in Cavalry Cemetery, St Louis.</p>\n<p>Other careers are less well documented, although the records held by the Archdiocese of St Louis provide a significant amount of information about their careers. Take for example, <a href="https://www.clericus.ie/person/35469">John Patrick Green (e)</a> born in Malahide, county Dublin in 1843 but who entered SPCM in 1863 for the diocese of Down and Connor. According to records in St Louis Green (e) served in Newtownards, county Down; in St Malachy’s College, Belfast as professor; and as admistrator of St Mary’s and St Malachy’s from 1878-1888. Green (e), who was ordained in 1867 by Cardinal Cullen,  arrived in St Louis in January 1893.</p>\n<p>Other Maynooth clerics who went to St Louis included three bishops, namely - <a href="../person/26003">Anthony O’Regan </a>and <a href="https://www.clericus.ie/person/34238%20">Patrick Feehan</a> , bishops of Chicago, and <a href="https://www.clericus.ie/person/38619">Peter Richard Kenrick</a> , Bishop of St Louis.</p>\n<p>In the coming weeks we will feature their careers as we delve further into the stories of Maynooth clerics in the USA.</p>',
        createdAt: '2021-07-29T23:43:10.354Z',
        highlight: false,
        highlightOrder: 0,
        featuredImage: '86588',
        createdBy: '72756',
        _id: '86587',
        permalink: 'maynooth-clerics-in-st-louis',
        category: [73686, 872],
        status: 'public',
        teaser: '',
        updatedAt: '2021-07-30T08:15:14.759Z',
        systemLabels: ['Article'],
        featuredImageDetails: {
          _id: '86588',
          filename: '800px-Archbishop_Patrick_Feehan.jpg',
          type: 'image',
          year: 2021,
          month: 7,
          hashedName: '131f20ab0b533cc1dbe9376e451585f5.jpg',
          paths: [
            {
              path: 'http://localhost:5100/uploads/2021/7/images/131f20ab0b533cc1dbe9376e451585f5.jpg',
              pathType: 'source',
            },
            {
              path: 'http://localhost:5100/uploads/2021/7/thumbnails/131f20ab0b533cc1dbe9376e451585f5.jpg',
              pathType: 'thumbnail',
            },
          ],
          createdBy: '72756',
          createdAt: '2021-07-30T08:12:46.869Z',
          updatedBy: '72756',
          updatedAt: '2021-07-30T08:12:46.869Z',
          label: 'undefined',
        },
        author: 'Ciaran Reilly',
      },
      {
        updatedBy: '532',
        label: "New Event Types: 'Last Will and Testament' and 'Lobbying'",
        content:
          '<p>The newest data added to the Clericus system is taken from three resources (a testimony and two wills dating from 1693, 1703 and c.1728 respectively) that relate to the Reverends <a href="77739">John Dempsey</a> and <a href="76511">Edward Murphy</a>. The ingestion of this data necessitated the creation of new event types called \'Lobbying\' and \'Last Will and Testament\' alongside several new relation types within the system.</p>\n<p><strong>Rev. John Dempsey</strong></p>\n<p>Born in Kildare in c.1641 and descended from the noble Dempseys of Clonmalier, the Rev. Dempsey’s life and association with the Catholic Church spanned a long and tumultuous period in Irish history. Dempsey was ordained in Ireland at Clonkeen in 1666 and later studied in France, where he was awarded his licentiate in theology from the Sorbonne. Upon his return to Ireland he served as PP of St. Michan’s and chancellor of the royal church of Christchurch. In 1693 a testimony was signed by six Irish priests based in Paris in favour of Dempsey’s promotion to a vacant Irish bishopric. Two of these priests, <a href="76535">Cornelius Nary</a> and <a href="77764">James Eustace</a>, would later serve under Dempsey’s episcopate, while a third, <a href="https://www.clericus.ie/person/86520">Bernard Dunne</a>, eventually returned to Ireland during the 1720s as bishop of Kildare and Leighlin and ‘unofficial’ coadjutor bishop to Edward Murphy.</p>\n<p>When the 1693 testimony in Dempsey’s favour was presented to the exiled <a href="86547">King James II</a>, Ireland had just emerged from a relatively short yet vicious period of conflict – this had included the battles of the Boyne and Aughrim, the latter perhaps the bloodiest ever fought on Irish soil, alongside the costly sieges of Limerick and Derry/Londonderry. The Jacobite defeat in Ireland meant that many Irish bishops either went into exile or were prevented from returning from the continent over the coming years. Indeed, the three remaining signatories of the testimony in Paris were the exiled bishops <a href="75167">James Lynch</a> of Tuam, <a href="74671">Dominic Burke</a> of Elphin and <a href="86518">John O’Moloney</a> of Limerick and Killaloe. The dwindling number of resident bishops on the island was a cause for concern, and the death in 1693 of the bishop of Kildare, <a href="81506">Edward Wesley</a>, only added to this problem. King James’ subsequent nomination of Dempsey to <a href="86519">Pope Innocent XII</a>, which unusually for the time went unopposed by other factions within the church, described him as a long serving priest, prudent and possessed of a dignified demeanour. </p>\n<p>John Dempsey was subsequently appointed as bishop of Kildare in November 1694. However, the state of the diocese and its cathedral town at that time gives a sense of the conditions and difficulties facing the new bishop. King James’ nomination of Dempsey related that the cathedral in Kildare town still existed but was held by the ‘heretics’. It was further reported that no Catholic dignitaries or canons were present to assist Dempsey, while the sacraments were being administered in private houses by missionary priests and pastors. The bishop had no episcopal residence either and could not count on any revenues for his support except for what could be collected by charity. Nevertheless, Dempsey’s responsibilities were extended a year later when he was appointed administrator of Leighlin diocese.</p>\n<p>Despite the difficulties he faced, Dempsey proved to be a capable figure and even managed to escape deportation under the 1697 Banishment Act. He would later successfully conceal his position within the church once again by registering as PP of Kilraney, Co. Kildare following the passing of the 1704 Registration Act. He represented one of only a handful of bishops who remained in Ireland during this period, and his importance was such that he became the de-facto co-administrator of the Archdiocese of Dublin alongside Edward Murphy. </p>\n<p><strong>Rev. Edward Murphy</strong></p>\n<p>The Reverend Nicholas Edward Murphy was another important figure within the Irish Catholic Church during this period. Born in 1651 and a native of Balrothery, Co. Dublin, Murphy received his education at Salamanca and was ordained in 1677 in Escorial (near Madrid) by James Lynch, Archbishop of Tuam. He returned to Ireland where he was prebendary of Clonmethan and precentor (1688). In 1685 he was secretary to a provincial synod convened in Dublin. Next, by papal provision he was named PP of St. Audoen’s (1687) and was instrumental in moving the parish to Cook Street in 1698. He was a member of the diocesan chapter from 1688 and was appointed Vicar General of the diocese of Dublin in 1698. Murphy escaped transportation under the 1697 Banishment Act and once again avoided detection in 1704 by registering as PP of St. Audeon’s under the clergy registration. Murphy’s star continued to rise over the coming years, becoming bishop of Kildare and Leighlin in 1715 and Archbishop of Dublin in 1724 until his death four years later.</p>\n<p> </p>\n<p><strong>Resources</strong></p>\n<p><em>Testimony</em></p>\n<p>The 1693 testimony is essentially a recommendation that might usually accompany a petition. John Dempsey may, for instance, have petitioned King James II for his promotion to bishop and the Paris testimony may have accompanied this. The testimony most definitely accompanied King James\' nomination of Dempsey to the Pope, as it is located in Rome\'s Propaganda Fide archive. A modern equivalent of this lobbying process can be seen in job applications: the applicant provides a potential employer with their Curriculum Vitae (petition) and character/professional references (testimony) are provided by other parties in support of this application. </p>\n<p>The 1693 testimony helps us to address an issue that had been identified concerning how best to represent information and relationships expressed within the different forms of lobbying prevalent during the early modern period. These types of sources survive in large numbers scattered across Irish and European archives. As such, they are an important source of data to the Clericus project, particularly in the way they capture networks, events and biographical information. </p>\n<p>To best capture this data, first it was necessary to create a new event type called \'Lobbying\'. Next, several new person-to-person and person-to-event relation types within the Clericus system were created also. Regarding the latter relation types, the existing ‘has participant/participated in’ relation was used to link those who composed the testimony with the lobbying event. The roles of the intended recipients or targets of the testimony, King James II and Pope Innocent XII, are expressed through the new relation ‘was received by/received’, while a further new relation in the form of ‘was beneficiary of/had beneficiary’ was created to express John Dempsey’s relationship with the lobbying event. A new person-to-person relation was also created between Dempsey and those who composed the testimony called ‘was recommended by/provided recommendation’. In future, a similar work package is planned to ingest data from a petition to help decide upon how to capture different relations within another dominant form of lobbying.</p>\n<p><em>Wills</em></p>\n<p>John Dempsey’s will, written in July 1703, bequeathed small sums of money to three priests, including two possible relatives named <a href="86300">Dominic Dempsey</a> and <a href="76343">Charles Dempsey</a>. Bequests were also left to lay individuals, such as the <a href="86425">Lady Anne Dempsey</a> (nee Bermingham), widow of Maximilian O’Dempsey, the last Viscount of Clanmalure (d.1690). John Dempsey and Anne Dempsey were quite closely connected: Dempsey lodged with the widow in 1698 and acted as her personal chaplain, while Lady Dempsey is named as sole executor and the main beneficiary of his will in 1703. Even from the short passage above, the reader may notice the various different relationships that are expressed in the will. Therefore, to capture these different relationships within the Clericus database meant creating a new event type called ‘last will and testament’ along with several new relation types. New relation types for the will event include ‘was executor of/had executor’, ‘bore witness to/had witness’ and ‘composed/was composed by’. Fortunately, the relation type ‘was beneficiary of/had beneficiary’ created for Dempsey’s testimony could be used again to link those who received bequests in the will. </p>\n<p>Edward Murphy’s will from c.1728 provides an interesting and valuable snapshot of his professional and lay networks at the time of his death. Including witnesses, a total of 26 individuals are named in the will. This includes 11 priests serving under Murphy at the time, several of whom are already present in the Clericus database, such as the future bishop of Dublin, <a href="76511">John Linegar</a>. Nearly a dozen family members are named in the will also as receiving bequests and/or acting as executors. Capturing these relationships within the database meant using the different person-to-event and person-to-person relation types already utilised in the Dempsey example. However, two new  person-to-person links were created, including ‘has servant/was servant to’ which expresses the relationship between Dempsey and his maid, <a href="86566">Mary Kelly</a>.</p>\n<p>Finally, the network linkages present in these sources permitted the identification of clear professional relationships amongst clerics, which are now captured using the additional person-to-person links 1) \'served under/was served by\' for priests who served under the episcopates of Dempsey and Murphy, and 2) \'served with\' to denote service between clerics of relatively equal standing within the church\'s hierarchy, as in the case of Dempsey and Murphy (Dempsey would technicaly represent the senior figure as a bishop, but the several key roles Murphy occupied within the Archdiocese of Dublin supported his own high standing within the church).</p>\n<p>Each of these resources permitted the Clericus project to further enrich individual careers to a degree not yet seen in the database by providing granular biographical data and important network linkages between entries within the system. In a wider sense, the addition of these resources is important for future steps in the project as they permitted the development of new and re-usable relation types for two of the most common resources that survive from this period.</p>\n<p> </p>\n<p><strong>Sources:</strong></p>\n<p>William Carrigan, ‘Catholic Episcopal Wills: In the Public Record Office, Dublin. 1683-1812’ in <em>Archivium Hibernicum</em>, iv (1915), pp 66-95, available <a href="https://www.jstor.org/stable/25485486?seq=1#metadata_info_tab_contents">here</a></p>\n<p>Michael Comerford, <em>Collections relating to the diocese of Kildare and Leighlin</em> (3 vols, Dublin, 1883), i, pp 72-3, available <a href="http://www.askaboutireland.ie/aai-files/assets/ebooks/193-195-198%20Collections%20Relating%20to%20the%20Dioceses%20of%20Kildare%20and%20Leighlin/195-Diocese%20of%20Kildare%20and%20Leighlin%20Vol%201.pdf">here</a></p>\n<p>Eric A. Derr, ‘The Irish Catholic Episcopal Corps, 1657-1829: A Prosopographical Analysis, Volume II’ (PHD Thesis, Maynooth University, 2013), available <a href="http://mural.maynoothuniversity.ie/7686/2/Final%20-%20Volume%202.pdf">here</a></p>\n<p>Benignus Millett, ‘A testimonial in favour of the Reverend John Dempsey, 16 July 1693’ in <em>Collectanea Hibernica</em>, no. 44/45 (2002/2003), pp 76-78.</p>\n<p>William P. Burke, <em>The priests in the penal times (1660-1760)</em> (Waterford, 1914), available <a href="https://archive.org/details/theirishpriestsi00burkuoft/page/n3/mode/2up">here</a></p>\n<p>Seán P. Donlan, ‘Murphy (Morphy), Dominic Edward’ in James McGuire and James Quinn (eds), <em>Dictionary of Irish biography</em> (Cambridge, 2009), available <a href="https://www.dib.ie/biography/murphy-morphy-dominic-edward-a6107">here</a></p>\n<p>Richard Fitzpatrick ‘Ireland’s ‘Popish Parish Priests’ in 1704’ (2021), available at <em><a href="../article/irelands-popish-parish-priest-in-1704-">Clericus</a></em></p>\n<p>Richard Fitzpatrick ‘‘Sculking about the towne’: The clergy of Dublin Diocese in 1698’ (2021), available at<em> <a href="../article/sculking-about-the-towne-the-clergy-of-dublin-diocese-in-1698">Clericus</a></em></p>\n<p>July 2021</p>',
        createdAt: '2021-07-28T16:48:41.914Z',
        highlight: false,
        highlightOrder: 0,
        createdBy: '532',
        featuredImage: '86583',
        _id: '86582',
        permalink: 'lobbying-and-last-wills-and-testaments',
        category: [872, 73686],
        status: 'public',
        teaser:
          '<p>The newest data added to the Clericus system is taken from three resources (a testimony and two wills), dating from 1693, 1703 and c.1728 respectively, that relate to the Reverends John Dempsey and Edward Murphy. </p>',
        updatedAt: '2021-08-30T17:22:44.083Z',
        systemLabels: ['Article'],
        featuredImageDetails: {
          _id: '86583',
          filename: 'Diocesan Wills.jpg',
          type: 'image',
          year: 2021,
          month: 7,
          hashedName: '22b02cd4f1197a563bc8b2c60a24c859.jpg',
          paths: [
            {
              path: 'http://localhost:5100/uploads/2021/7/images/22b02cd4f1197a563bc8b2c60a24c859.jpg',
              pathType: 'source',
            },
            {
              path: 'http://localhost:5100/uploads/2021/7/thumbnails/22b02cd4f1197a563bc8b2c60a24c859.jpg',
              pathType: 'thumbnail',
            },
          ],
          createdBy: '532',
          createdAt: '2021-07-28T17:10:55.533Z',
          updatedBy: '532',
          updatedAt: '2021-07-28T17:10:55.533Z',
          label: 'undefined',
        },
        author: 'Richard Fitzpatrick',
      },
      {
        updatedBy: '532',
        label:
          '‘Sculking about the towne’: The clergy of Dublin Diocese in 1698',
        content:
          '<p> </p>\n<p> </p>\n<p><strong>                                      </strong></p>\n<p><strong>Context</strong></p>\n<p>The ‘Banishment Act’ (9 Will. III, c.1) of 1697 represented the first piece of legislation passed since the treaty of Limerick (1691) that directly affected the practice of the Catholic religion in Ireland. Peace on the island had been overshadowed by continued hostilities between Britain and France until 1697, thereby fuelling the fear amongst Ireland’s ruling Protestant minority of a Jacobite invasion with French assistance. The Irish Catholic clergy (and Catholics in general) were viewed as potential supporters of any such invasion, and from 1695 steps were taken by the Irish Parliament to introduce legal restrictions to address the threat posed by the island’s numerous clergy. The regular clergy (i.e. monks and friars) were initially perceived as the most serious threat to security, given ‘they bear a greater sway amongst the people than the secular priests and are more irreconcilable to their majesties’ government … Wherever there is any commotion they are not only privy to it, but foment it.’ The scope of the act was later expanded to banish bishops and all others who exercised ecclesiastical jurisdiction within the church’s hierarchy (i.e. vicars and deans).</p>\n<p>The eventual 1697 act gave regulars and the secular hierarchy until 1 May 1698 to lodge themselves in one of several Irish ports ‘until there shall be conveniency of shipping for their transportation into some parts beyond seas’. Those who remained at large after 1 May would, if apprehended, ‘suffer imprisonment, and remain in prison until transported out of his Majesty’s dominions’, while any who subsequently returned to the shores of Ireland ‘shall be guilty of high treason.’ One English observer forecasted that this would slowly undermine and eventually collapse the Catholic Church in Ireland, since ‘every parish is allowed its [secular] priest; but when he dies, there being none to ordain a new one, it must remain without; and this will be the state of the whole kingdom in a little time when the present set of priests shall be extinct’. Although this did not eventually occur, Catholics in Ireland occupied a weakened position during the 1690s and, at base, the 1697 act sought to exploit this situation to help secure the island\'s Protestant interest.</p>\n<p>To implement the act a census was taken of the Catholic clergy in each county, city and town, distinguishing regulars from seculars. For this it was possible to use records from a recently imposed poll tax, which levied a particular rate on persons in ‘Romish orders’. To gain further intelligence on ‘priests and fryars’ in their respective districts, the commissioners and clerks charged with gathering this information were directed in late 1697 to ‘inform themselves by such other ways and meanes as they see fitt’. The total number of Catholic clergy returned was 872 seculars and 495 regulars, making a total of 1,367 – though the true number may have been several hundred higher. Of the different lists compiled across Ireland, only the returns for Dublin diocese drawn up on 2 March 1698 have survived, and it is this information that has been added to the Clericus database. This was transcribed from the version reproduced in Rev. William P. Burke\'s <em>Priests in the penal times </em>(pp 120-127), which in turn was copied from the original that had passed to the Protestant Archbishop of Dublin, Narcissus Marsh (1638-1713).</p>\n<p> </p>\n<p><strong>Content</strong></p>\n<p>The surviving 1698 diocesan list covers Dublin county and parts of the neighbouring counties of Kildare and Wicklow. The document records information by parish on a total of 116 clerics, both regular and secular, based within the diocese of Dublin. Of these, 48 correspond with and help to enrich existing biographical entries in the Clericus database taken from the <a href="../article/irelands-popish-parish-priest-in-1704-">1704 registration</a> of the secular clergy. Furthermore, over two dozen regulars were recorded in 1698 split amongst the Dominicans (8), Franciscans (9), Jesuits (4), Augustinians (5), Carmelites (2) and Capuchins (1). A further 10 possible regulars were identified but without any specific religious order noted. The clergy list also provides places of abode for many, including the names and addresses of 20 lay individuals who provided lodgings to specific priests. This included <a href="76465">Patrick Luttrell</a> who was ‘residing at <a href="75406">William Daly\'s</a> at the Sign of the Sun in Cook St.’ and <a href="77764">James Eustace</a> ‘living with Col. <a href="86309">Richard Eustace</a> of Ballymore Eustace’. Of further interest regarding places of abode are the convents maintained in Dublin City by the Carmelites (Corn Market), Dominicans (Cook St.) and Augustinians (Cook St.) just prior to the 1697 act’s implementation. Elsewhere in the diocese, an alleged regular cleric, <a href="86313">Daniel McCann</a>, split his time between Lucan and St. Wolstan’s near Celbridge, while three Dominicans reputedly resided at a convent in <a href="../organisation/86344">Arklow</a>. However, the intelligence gathered for the authorities was not perfect. This is illustrated by the 14 regulars whose exact whereabouts in the diocese by March 1688 were unknown, but were believed to be either ‘now in the country’ or ‘supposed to be sculking about the towne\' (Dublin).</p>\n<p><em>Regular Clergy</em></p>\n<p>It appears that a large percentage of Ireland’s regular clergy complied with the law and were eventually deported. A similar fate was apparently also shared by most of the regular clergy recorded for Dublin. The early months of 1698 saw a reported 424 priests deported from the ports of Dublin, Cork, Galway and Waterford to Catholic countries on the continent. The exiled King James II himself noted in correspondence in mid-March 1698 how ‘the unhappy religious are fleeing in crowds to France’. James estimated that at least 400 had undertaken the journey to France, while his wife Mary of Modena calculated an additional 300 clerics had been ‘hunted’ out of Ireland to Italy, Spain, Portugal and Flanders. By late 1698 it was found that a total of 383 banished regular clergy alone were residing in the Paris area and were dependent for their survival on donations from Pope Innocent XII and other wealthy patrons.</p>\n<p>The fortunes of those regulars who initially remained in Ireland after the 1 May 1698 deadline were equally grim, with surviving accounts highlighting many examples of those who were sought out and arrested. A major incentive driving this was the reward offered by the authorities from late 1701 to anyone who apprehended a regular cleric (£10), dean/vicar general (£30) or bishop (£100). The promise of these bounties would in turn give rise in society to notorious and despised priest hunters, such as John Garzia, Barry Lowe, Edward Tyrrell and Seán na Sagart (John of the priest). Based on known examples, regulars who were eventually brought to trial for breaching the 1697 act fared worse than their counterparts amongst the secular hierarchy. Many were tried, convicted and sentenced to transportation. However, whether by design or circumstance, the response of the authorities was not always to impose immediate deportation, but instead to hold convicted regulars for several years amid often squalid conditions in gaols such as Newgate and the Black Dog in Dublin. For instance, <a href="82552">Edward Chamberlain</a>, a Jesuit residing at Cook St. in 1698, was apprehended in 1701 and was still being held in Newgate two years later.</p>\n<p>Dependence on a handful of justices of the peace, sheriffs or hated priest hunters to apprehend illusive clergy was not a practical long-term solution, nor was it always conducive to maintaining order within society. Therefore, the actual ability and energy needed to enforce the Banishment Act steadily weakened over time. Many regulars found their way back to Irish shores in the years that followed, including in 1723 when no fewer than 17 returning friars were arrested in Dublin. Despite these intermittent episodes of arrest and prosecution, by 1731 an Irish House of Lords investigation and report found that at least 250 regulars were then residing in Ireland. In Dublin, in St. Catherine’s parish, it was reported that the Augustinians and Carmelites had re-established friaries with a dozen members each, while more regulars had returned to residing in Cook St. and Bridge St. Indeed, the number of regulars on the island by mid-century was so high that religious orders were barred by the Catholic Church itself from accepting novices in Ireland. There were literally too many priests on the island.</p>\n<p><em>Bishops and secular clergy</em></p>\n<p>Of the bishops and secular hierarchy liable for deportation under the 1697 act, the Dublin census lists the Vicar General of Dublin, <a href="76511">Edward Murphy</a>, and the Bishop of Kildare and Leighlin, <a href="77739">John Dempsey</a>. Despite drawing the attention of priest hunters, both individuals escaped transportation and concealed their true positions within the church by registering in 1704 as parish priests for St. Audeon’s and Kilraney respectively. The few other remaining bishops in Ireland were not always as fortunate. The aging Bishop <a href="74760">John Sleyne</a> of Cork and Cloyne was imprisoned for five years in Cork Gaol before his eventual transportation to Portugal in 1703. However, it is said that he continued to celebrate mass and even ordain priests from his cell during his prolonged incarceration - this latter belief is supported by the 6 ordinations the bishop performed between 1698 and 1701 based on the 1704 registration. Of two other bishops who remained in Ireland, <a href="81074">Edward Comerford</a> of Cashel found protection in Tipperary under the Matthews of Thurles and Annfield. Based on the 1704 data within the Clericus database, the other bishop, <a href="74907">Maurice Donnellan</a> of Clonfert, ordained at least 7 priests in Ireland between 1698 and 1701, but was eventually apprehended in 1703. Nevertheless, soon after, while being escorted through Galway, Donnellan was rescued by a ‘great multitude’ of 300 people who set upon his captors ‘with great force and violence and against the known laws of this kingdom’.</p>\n<p>The majority of the secular clergy of Dublin (parish priests and their curates) recorded in 1698 faced no restrictions under the Banishment Act. Nevertheless, their presence in the 1698 list helps to enrich our knowledge of the careers of many who were later recorded again in the parish priest registration of 1704. For instance, <a href="76305">John Corcoran</a> was ordained in 1693 in Lisbon before returning on the Irish Mission, acting in 1698 as curate for the parishes of Balscaddan and Balrothery under an eighty-year-old blind and lame priest named <a href="86262">Andrew Finglas</a>. By 1704 Corcoran had succeeded to both parishes, and no doubt future sources added to the Clericus database will help to illuminate the remainder of his clerical career, and perhaps that of Andrew Finglas also. Therefore, although the 1698 clergy list for Dublin is the smallest resource added to the Clericus database to date, it provides another important building block in our understanding of the identities, careers and associations of Ireland\'s clergy during a turbulent period in their history.</p>\n<p> </p>\n<p><strong>Transcription of the text and data ingestion</strong></p>\n<p>The 1698 Dublin clergy list was compiled using information gathered from various sources by multiple individuals. Furthermore, these commissioners and clerks were essentially outsiders attempting to gain intelligence on a relatively hostile and increasingly secretive population. As a result, although a relatively accurate document for its time, the final list drawn up on 2 March 1698 contains several errors, including duplicate entries for certain clerics. Oftentimes these duplicates include variation of spelling in first names and surnames or the absence of one name or the other. Where possible, these examples were amalgamated into a single entry, such as in the case of <a href="86317">Henry Dalton</a> who appears in the list twice. In other instances, where possible duplication in the list was identified, but could not be proven beyond a reasonable doubt, it was decided to retain two separate entries. However, it was deemed important that these possible and probable linkages between relevant biographical entries should be captured within the Clericus database. This led to the creation of two new person-to-person relation types within the database. Thus, where there was a strong likelihood that two entries related to the same person, the relationship type ‘probably the same person as’ was used to link both individuals. This can be seen in the examples of <a href="86397">William Cavenah</a><strong>/</strong><a href="82462">William Cavenogh</a> and <a href="76424">Patrick Gilmore</a><strong>/</strong><a href="86379">Patrick Gilmare</a>. If, on the other hand, a less certain linkage between two individuals was identified, the relationship type ‘possibly the same person as’ was used to represent this uncertainty, as in the cases of <a href="86276">Kale</a><strong>/</strong><a href="86289">Cole</a>, <a href="72687">Brian</a><strong>/</strong><a href="77851">Bryan McCabe</a> and <a href="86313">Daniel McCann</a><strong>/</strong><a href="86356">Daniel Markee (alias Marcan)</a>.</p>\n<p>A second issue faced during the data ingestion phase was the significant overlap between the new 1698 Dublin list and the previously ingested 1704 clergy registration data. This essentially meant searching and cross referencing the existing 1704 clergy in the database with each name from the new 1698 list. Four dozen definite matches were made during this process. All such data from the 1698 list was subsequently added to its corresponding database entry (for example, <a href="76327">William Dardis</a> and <a href="76211">Thomas Austin</a>). However, the nature of the information, followed by the fact it was compiled over three hundred years ago, meant that the previously described issue of possible and probable matches between individuals was encountered once again, this time across sources/datasets. In response, the same solution using the new person-to-person linkages described above was utilised, as can be observed in the probable case of <a href="86272">Bartholomew Scully</a><strong>/</strong><a href="76591">Bartholomew Scallery</a> and the possible <a href="86431">Patrick</a><strong>/</strong><a href="82505">Patrick Hagan</a> and <a href="86229">John Jones</a><strong>/</strong><a href="76444">Nicholas Jones</a>.</p>\n<p>Overall, despite representing the smallest resource added to the database thus far, the 1698 Dublin clergy dataset is important to future phases of the Clericus project. Insights gained and decisions made during its transcription and ingestion will help the Clericus team to identify and address issues surrounding data duplication once larger and more complex datasets are added to the database. These developments will help to maintain data integrity by refining methods to identify and capture ambiguity within and between our data sources.</p>\n<p> </p>\n<p><strong>Sources:</strong></p>\n<p>J. G. Simms, ‘The Bishops\' Banishment Act of 1697 (9 Will. III, c. 1)’ in <em>Irish Historical Studies</em>, lxvi (Sept., 1970), pp 185-199.</p>\n<p>Thomas O’Connor, ‘The Catholic Church and Catholics in an era of sanctions and restraints, 1690–1790’ in James Kelly (ed.), <em>The Cambridge History of Ireland</em>,<em> vol. iii, 1730–1880</em> (Cambridge, 2018), pp 257–279.</p>\n<p>Ian McBride, <em>Eighteenth-Century Ireland: the isle of slaves</em> (Dublin, 2009).</p>\n<p>James Kelly, \'Disappointing the boundless ambition of France\': Irish Protestants and the fear of invasion, 1661-1815\' in <em>Studia Hibernica</em>, xxxvii (2011), pp 27-105.</p>\n<p>Eric A. Derr, ‘The Irish Catholic Episcopal Corps, 1657-1829: A Prosopographical Analysis, Volume II’ (PHD Thesis, Maynooth University, 2013), available <a href="http://mural.maynoothuniversity.ie/7686/">here</a></p>\n<p>Maureen Wall, <em>The penal laws 1691-1760</em> (Dundalk, 1967).</p>\n<p>Kevin McGrath, \'John Garzia, a noted priest-catcher and his activities, 1717-23\' in <em>The Irish Ecclesiastical Record</em> (Series 5), lxxii (1949), pp 494-514.</p>\n<p>Kevin McGrath, \'The clergy of Dublin in 1695\' in <em>The Irish Ecclesiastical Record</em>, Series 5, lxxiv (1950), pp 193-200.</p>\n<p>William P. Burke, <em>The priests in the penal times (1660-1760)</em> (Waterford, 1914), available <a href="https://archive.org/details/theirishpriestsi00burkuoft/page/n3/mode/2up">here</a></p>\n<p>Benignus Millett, \'A testimonial in favour of the Reverend John Dempsey, 16 July 1693\' in <em>Collectanea Hibernica</em>, no. 44/45 (2002/2003), pp 76-78.</p>\n<p>J. McCaffrey (ed.), ‘Report on the State of Popery, Ireland, 1731’ in <em>Archivium Hibernicum</em>, i-iv (1912-1915). </p>\n<p>Betty Brunkard, ‘A Snippet of Dublin History (Part 7) – Newgate Prison’ (2014), available <a href="http://www.frg.ie/local-history/a-snippet-of-dublin-history-part-7-newgate-prison/">here</a></p>\n<p>June 2021</p>\n<p> </p>\n<p> </p>',
        createdAt: '2021-07-01T23:04:12.248Z',
        highlight: false,
        highlightOrder: 0,
        createdBy: '532',
        featuredImage: '86529',
        _id: '76438',
        permalink:
          'sculking-about-the-towne-the-clergy-of-dublin-diocese-in-1698',
        category: [73686, 872],
        status: 'public',
        teaser:
          "<p>Learn more about the fortunes of 116 of Dublin Diocese's clergy under the Banishment Act of 1697.</p>",
        updatedAt: '2021-07-29T17:09:01.394Z',
        systemLabels: ['Article'],
        featuredImageDetails: {
          _id: '86529',
          filename: 'Mass Penal Laws.jpg',
          type: 'image',
          year: 2021,
          month: 7,
          hashedName: '7443770ca29f12ed112b814fb7f93162.jpg',
          paths: [
            {
              path: 'http://localhost:5100/uploads/2021/7/images/7443770ca29f12ed112b814fb7f93162.jpg',
              pathType: 'source',
            },
            {
              path: 'http://localhost:5100/uploads/2021/7/thumbnails/7443770ca29f12ed112b814fb7f93162.jpg',
              pathType: 'thumbnail',
            },
          ],
          createdBy: '532',
          createdAt: '2021-07-20T19:25:49.832Z',
          updatedBy: '532',
          updatedAt: '2021-07-20T19:25:49.832Z',
          label: 'undefined',
        },
        author: 'Richard Fitzpatrick',
      },
    ],
    totalItems: 14,
    totalPages: 3,
  },
  error: [],
  msg: 'Query results',
};

export const welcome = {
  status: true,
  data: {
    currentPage: 1,
    data: {
      category: {
        _id: '28943',
        label: 'Welcome Fáilte Vale',
        permalink: 'welcome-filte-vale',
        parentId: 0,
        status: 'public',
        createdBy: '432',
        createdAt: '2020-07-06T09:39:16.804Z',
        updatedBy: '432',
        updatedAt: '2020-07-06T09:39:18.509Z',
        categories: [
          {
            _id: '28943',
            label: 'Welcome Fáilte Vale',
            permalink: 'welcome-filte-vale',
            parentId: 0,
            status: 'public',
            createdBy: '432',
            createdAt: '2020-07-06T09:39:16.804Z',
            updatedBy: '432',
            updatedAt: '2020-07-06T09:39:18.509Z',
          },
        ],
        children_categories: [],
      },
      articles: [
        {
          updatedBy: '53930',
          label: 'Welcome Fáilte Vale',
          content:
            '<p>Welcome to <strong><em>Clericus</em></strong>, the digital gateway to Ireland’s oldest and most diverse professional cohort: the clergy. In this first phase of the project, biographical records of 13,000 individuals associated with St Patrick’s College Maynooth since its foundation in 1795 are made available to visitors, many of them through unique photographic records, accumulated by the College since the 1880s. Future phases will include the capture of photographic records held in other Irish seminaries and religious orders, and the digital mapping of Ireland’s international clerical diaspora. Thanks to a combination of ground breaking digital technology and first-class historical research, visitors have access to a uniquely important archive and an absorbing cultural experience.</p>',
          createdAt: '2020-07-02T10:52:29.594Z',
          highlight: false,
          highlightOrder: 0,
          featuredImage: '33537',
          createdBy: '531',
          _id: '28394',
          permalink: 'welcome-filte-vale',
          category: [28943],
          status: 'public',
          teaser:
            '<p>Welcome to <strong><em>Clericus</em></strong>, the digital gateway to Ireland’s oldest and most diverse professional cohort: the clergy. In this first phase of the project, biographical records of 13,000 individuals associated with St Patrick’s College Maynooth since its foundation in 1795 are made available to visitors, many of them through unique photographic records, accumulated by the College since the 1880s. Future phases will include the capture of photographic records held in other Irish seminaries and religious orders, and the digital mapping of Ireland’s international clerical diaspora. Thanks to a combination of ground breaking digital technology and first-class historical research, visitors have access to a uniquely important archive and an absorbing cultural experience.</p>',
          updatedAt: '2021-06-11T11:48:47.622Z',
          systemLabels: ['Article'],
          featuredImageDetails: {
            _id: '33537',
            filename: 'logo-transparentx400.jpg',
            type: 'image',
            year: 2020,
            month: 7,
            hashedName: '196b7c4b3f5674a03158e2733faadcb2.jpg',
            paths: [
              {
                path: 'http://localhost:5100/uploads/2020/7/images/196b7c4b3f5674a03158e2733faadcb2.jpg',
                pathType: 'source',
              },
              {
                path: 'http://localhost:5100/uploads/2020/7/thumbnails/196b7c4b3f5674a03158e2733faadcb2.jpg',
                pathType: 'thumbnail',
              },
            ],
            createdBy: '432',
            createdAt: '2020-07-02T10:59:18.939Z',
            updatedBy: '432',
            updatedAt: '2020-07-02T10:59:18.939Z',
            label: 'undefined',
          },
          author: "Tom O'Connor",
        },
      ],
    },
    totalItems: 1,
    totalPages: 1,
  },
  error: [],
  msg: 'Query results',
};
