export const organisationData = {
  status: true,
  data: {
    createdAt: '2020-03-11T12:57:06.254Z',
    updatedBy: '532',
    createdBy: '532',
    labelSoundex: 'D145',
    description: '',
    label: 'Dublin',
    _id: '189',
    alternateAppelations: [
      '{"label":"Dublinensis","note":"","language":""}',
      '{"label":"Baile Átha Cliath","note":"","language":""}',
      '{"label":"Ath Cliath","note":"","language":""}',
    ],
    organisationType: 'Diocese',
    updatedAt: '2021-06-11T10:38:00.374Z',
    status: 'public',
    events: [
      {
        _id: '486928',
        term: {
          label: 'isRelatedTo',
        },
        ref: {
          createdAt: '2021-08-10T11:55:14.923Z',
          updatedBy: '532',
          createdBy: '532',
          description: '',
          label: 'Ministry',
          eventType: '21267',
          status: 'public',
          updatedAt: '2021-08-10T11:55:14.923Z',
          _id: '86808',
        },
        temporal: [
          {
            _id: '486929',
            term: {
              label: 'hasTime',
            },
            ref: {
              createdAt: '2021-08-10T11:56:05.712Z',
              updatedBy: '532',
              createdBy: '532',
              endDate: '31-12-1605',
              format: '',
              label: 'c.1605',
              startDate: '01-01-1605',
              updatedAt: '2021-08-10T11:56:05.712Z',
              _id: '86809',
            },
          },
        ],
        spatial: [
          {
            _id: '486933',
            term: {
              label: 'hasLocation',
            },
            ref: {
              country: 'Ireland',
              note: '',
              updatedBy: '532',
              latitude: '53.3497645',
              postalCode: '',
              locality: '',
              locationType: 'City',
              label: 'Dublin',
              createdAt: '2020-07-12T16:08:12.560Z',
              createdBy: '53930',
              streetAddress: '',
              _id: '54350',
              region: 'County Dublin',
              updatedAt: '2021-06-09T13:45:37.164Z',
              longitude: '-6.2602732',
            },
          },
        ],
        organisations: [
          {
            _id: '486927',
            term: {
              label: 'hasRelation',
            },
            ref: {
              createdAt: '2020-03-11T12:57:06.254Z',
              updatedBy: '532',
              createdBy: '532',
              labelSoundex: 'D145',
              description: '',
              label: 'Dublin',
              _id: '189',
              alternateAppelations: [
                '{"label":"Dublinensis","note":"","language":""}',
                '{"label":"Baile Átha Cliath","note":"","language":""}',
                '{"label":"Ath Cliath","note":"","language":""}',
              ],
              organisationType: 'Diocese',
              updatedAt: '2021-06-11T10:38:00.374Z',
              status: 'public',
            },
          },
        ],
        people: [
          {
            _id: '486931',
            term: {
              label: 'hasParticipant',
            },
            ref: {
              lastName: 'Mulrony',
              updatedBy: '532',
              honorificPrefix: [''],
              description: '',
              label: 'Andrew Mulrony',
              alternateAppelations: [
                '{"appelation":"","firstName":"Andreas","middleName":"","lastName":"O Mullruana","note":"","language":{"value":"la","label":"Latin"}}',
              ],
              createdAt: '2021-02-15T11:16:25.699Z',
              firstName: 'Andrew',
              createdBy: '532',
              middleName: '',
              _id: '72539',
              lnameSoundex: 'M465',
              fnameSoundex: 'A536',
              personType: 'Clergy',
              status: 'public',
              updatedAt: '2021-02-15T11:16:54.419Z',
            },
          },
        ],
      },
    ],
    organisations: [
      {
        _id: '377239',
        term: {
          label: 'hasPart',
        },
        ref: {
          createdAt: '2021-05-13T14:23:16.505Z',
          updatedBy: '532',
          createdBy: '432',
          labelSoundex: 'I520',
          label: 'Inch',
          alternateAppelations: [],
          organisationType: 'Parish',
          updatedAt: '2021-05-13T22:18:19.234Z',
          status: 'public',
          _id: '82491',
        },
      },
    ],
    people: [
      {
        _id: '376805',
        term: {
          label: 'isAffiliationOf',
        },
        ref: {
          lastName: '',
          updatedBy: '532',
          description: '',
          honorificPrefix: [''],
          label: 'Brian ',
          alternateAppelations: [],
          createdAt: '2021-06-28T13:22:05.528Z',
          firstName: 'Brian',
          createdBy: '532',
          middleName: '',
          _id: '72687',
          fnameSoundex: 'B650',
          lnameSoundex: '',
          personType: 'Clergy',
          status: 'public',
          updatedAt: '2021-06-29T16:17:40.701Z',
        },
      },
    ],
    resources: [],
    classpieces: [],
    spatial: [
      {
        _id: '82897',
        term: {
          label: 'hasItsEpiscopalSeeIn',
        },
        ref: {
          country: 'Ireland',
          note: '',
          updatedBy: '532',
          latitude: '53.3497645',
          postalCode: '',
          locality: '',
          locationType: 'City',
          label: 'Dublin',
          createdAt: '2020-07-12T16:08:12.560Z',
          createdBy: '53930',
          streetAddress: '',
          _id: '54350',
          region: 'County Dublin',
          updatedAt: '2021-06-09T13:45:37.164Z',
          longitude: '-6.2602732',
        },
      },
    ],
  },
  error: [],
  msg: 'Query results',
};

export const organisationsData = {
  status: true,
  data: {
    currentPage: 1,
    data: [
      {
        createdAt: '2020-10-16T16:39:07.944Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'A442',
        description: '',
        label: 'All Hallows College (Dublin)',
        _id: '1910',
        alternateAppelations: [],
        organisationType: 'SeminaryCollege',
        status: 'public',
        updatedAt: '2021-06-11T13:11:34.748Z',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-09-15T17:40:41.589Z',
        updatedBy: '532',
        createdBy: '532',
        labelSoundex: 'A616',
        description: '',
        _id: '87200',
        label: 'Arbour Hill Prison Dublin',
        alternateAppelations: [],
        organisationType: 'Prison',
        status: 'public',
        updatedAt: '2021-09-15T19:27:07.386Z',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2020-03-11T12:57:06.254Z',
        updatedBy: '532',
        createdBy: '532',
        labelSoundex: 'D145',
        description: '',
        label: 'Dublin',
        _id: '189',
        alternateAppelations: [
          '{"label":"Dublinensis","note":"","language":""}',
          '{"label":"Baile Átha Cliath","note":"","language":""}',
          '{"label":"Ath Cliath","note":"","language":""}',
        ],
        organisationType: 'Diocese',
        updatedAt: '2021-06-11T10:38:00.374Z',
        status: 'public',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-01-14T15:20:55.405Z',
        updatedBy: '532',
        createdBy: '532',
        labelSoundex: 'D145',
        description: '',
        label: 'Dublin',
        _id: '71941',
        alternateAppelations: [],
        organisationType: 'County',
        status: 'public',
        updatedAt: '2021-06-11T10:59:23.453Z',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-06-08T14:22:50.576Z',
        updatedBy: '532',
        createdBy: '532',
        labelSoundex: 'D145',
        description: '',
        label: 'Dublin City',
        alternateAppelations: [],
        status: 'public',
        organisationType: 'City',
        updatedAt: '2021-06-08T14:22:50.576Z',
        _id: '81146',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-06-28T10:47:48.589Z',
        updatedBy: '532',
        createdBy: '532',
        labelSoundex: 'N353',
        description: '',
        label: 'Newtown (Dublin)',
        _id: '86380',
        alternateAppelations: [
          '{"label":"Newtown on the strand","note":"","language":""}',
        ],
        organisationType: 'Townland',
        status: 'public',
        updatedAt: '2021-06-28T10:52:44.182Z',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-09-15T18:37:48.006Z',
        updatedBy: '532',
        createdBy: '532',
        labelSoundex: 'S231',
        description: '',
        label: 'Society of Dublin Painters',
        alternateAppelations: [],
        organisationType: 'Society',
        status: 'public',
        updatedAt: '2021-09-15T18:37:48.006Z',
        _id: '87216',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:08.238Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S353',
        description: '',
        _id: '74143',
        label: "St. Andrew's (Dublin)",
        alternateAppelations: ['{"label":"St. Andrew\'s"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-06-25T09:48:32.238Z',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-06-25T09:45:04.652Z',
        updatedBy: '532',
        createdBy: '532',
        labelSoundex: 'S335',
        description: '',
        label: "St. Audeon's (Dublin)",
        alternateAppelations: [],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-06-25T09:45:04.652Z',
        _id: '86348',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:09.153Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S316',
        label: "St. Bride's (Dublin)",
        alternateAppelations: ['{"label":"St. Brides"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:36.157Z',
        _id: '74145',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:14.308Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S323',
        label: "St. Catherine's (Dublin)",
        alternateAppelations: ['{"label":"St. Katherin\'s"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:36.207Z',
        _id: '74155',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:11.796Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S325',
        label: "St. James' (Dublin)",
        alternateAppelations: ['{"label":"St. James\'s Parish"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:36.372Z',
        _id: '74150',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:12.674Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S325',
        label: "St. John's (Dublin)",
        alternateAppelations: ['{"label":"St. John\'s"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:36.450Z',
        _id: '74152',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:15.143Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S321',
        label: "St. Kevin's (Dublin)",
        alternateAppelations: ['{"label":"St. Kevin\'s"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:36.654Z',
        _id: '74157',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:17.221Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S356',
        label: "St. Margaret's (Dublin)",
        alternateAppelations: ['{"label":"St. Margarets"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:36.712Z',
        _id: '74161',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:17.892Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S356',
        label: "St. Mary's (Dublin)",
        alternateAppelations: ['{"label":"St. Maries"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:36.763Z',
        _id: '74162',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:21.920Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S352',
        label: 'St. Michael of Pauls (Dublin)',
        alternateAppelations: ['{"label":"St. Michael of Pauls, Monkstowne"}'],
        organisationType: 'Parish',
        updatedAt: '2021-05-13T22:19:36.851Z',
        status: 'public',
        _id: '74170',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:23.130Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S352',
        label: "St. Michael's (Dublin)",
        alternateAppelations: ['{"label":"St. Michael\'s"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:36.877Z',
        _id: '74172',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:24.069Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S352',
        label: "St. Michan's (Dublin)",
        alternateAppelations: ['{"label":"St. Michans Oxmand-town"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:36.933Z',
        _id: '74174',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:25.867Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S352',
        label: "St. Nicholas' within (Dublin)",
        alternateAppelations: ['{"label":"St. Nicholas within"}'],
        organisationType: 'Parish',
        updatedAt: '2021-05-13T22:19:37.095Z',
        status: 'public',
        _id: '74178',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:26.249Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S352',
        label: "St. Nicholas' without (Dublin)",
        alternateAppelations: ['{"label":"St. Nicholas without"}'],
        organisationType: 'Parish',
        updatedAt: '2021-05-13T22:19:37.112Z',
        status: 'public',
        _id: '74179',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:30.010Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S314',
        label: "St. Paul's (Dublin)",
        alternateAppelations: ['{"label":"St. Pauls"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:37.204Z',
        _id: '74187',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T11:04:25.171Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S313',
        label: "St. Peter's (Dublin)",
        alternateAppelations: ['{"label":"St. Peter\'s"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:37.289Z',
        _id: '76609',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-05-13T10:03:32.686Z',
        updatedBy: '532',
        createdBy: '432',
        labelSoundex: 'S361',
        label: "St. Werburgh's (Dublin)",
        alternateAppelations: ['{"label":"St. Warborough\'s"}'],
        organisationType: 'Parish',
        status: 'public',
        updatedAt: '2021-05-13T22:19:37.352Z',
        _id: '74193',
        systemLabels: ['Organisation'],
        resources: [],
      },
      {
        createdAt: '2021-09-15T09:43:28.718Z',
        updatedBy: '532',
        createdBy: '532',
        labelSoundex: 'U516',
        description: '',
        label: 'University College Dublin (UCD)',
        alternateAppelations: [],
        organisationType: 'University',
        updatedAt: '2021-09-15T09:43:28.718Z',
        status: 'public',
        _id: '87170',
        systemLabels: ['Organisation'],
        resources: [],
      },
    ],
    totalItems: 25,
    totalPages: 1,
  },
  error: [],
  msg: 'Query results',
};
